// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moitable.proto

package db // import "."

/*
d:\Go\test\src\nRIC\api\v1\pb\db>protoc.exe ../msgdef.proto ./dbsvc.proto --go_out=plugins=grpc:. -I../. -I./.
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 管理对象实例表
type MOITable struct {
	// Unique integer identifier of the moi table
	XappID        uint32  `protobuf:"varint,1,opt,name=XappID,proto3" json:"XappID,omitempty"`
	XappVer       float32 `protobuf:"fixed32,2,opt,name=XappVer,proto3" json:"XappVer,omitempty"`
	XappName      string  `protobuf:"bytes,3,opt,name=XappName,proto3" json:"XappName,omitempty"`
	Functions     string  `protobuf:"bytes,4,opt,name=Functions,proto3" json:"Functions,omitempty"`
	RunningStatus string  `protobuf:"bytes,5,opt,name=RunningStatus,proto3" json:"RunningStatus,omitempty"`
	IsReady       string  `protobuf:"bytes,6,opt,name=IsReady,proto3" json:"IsReady,omitempty"`
	Topic         string  `protobuf:"bytes,7,opt,name=Topic,proto3" json:"Topic,omitempty"`
	// Date and time to remind the moi table
	Reminder             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MOITable) Reset()         { *m = MOITable{} }
func (m *MOITable) String() string { return proto.CompactTextString(m) }
func (*MOITable) ProtoMessage()    {}
func (*MOITable) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{0}
}
func (m *MOITable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITable.Unmarshal(m, b)
}
func (m *MOITable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITable.Marshal(b, m, deterministic)
}
func (dst *MOITable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITable.Merge(dst, src)
}
func (m *MOITable) XXX_Size() int {
	return xxx_messageInfo_MOITable.Size(m)
}
func (m *MOITable) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITable.DiscardUnknown(m)
}

var xxx_messageInfo_MOITable proto.InternalMessageInfo

func (m *MOITable) GetXappID() uint32 {
	if m != nil {
		return m.XappID
	}
	return 0
}

func (m *MOITable) GetXappVer() float32 {
	if m != nil {
		return m.XappVer
	}
	return 0
}

func (m *MOITable) GetXappName() string {
	if m != nil {
		return m.XappName
	}
	return ""
}

func (m *MOITable) GetFunctions() string {
	if m != nil {
		return m.Functions
	}
	return ""
}

func (m *MOITable) GetRunningStatus() string {
	if m != nil {
		return m.RunningStatus
	}
	return ""
}

func (m *MOITable) GetIsReady() string {
	if m != nil {
		return m.IsReady
	}
	return ""
}

func (m *MOITable) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MOITable) GetReminder() *timestamppb.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// Request data to create new moi table
type MOITableInsertRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Task entity to add
	MoiTable             *MOITable `protobuf:"bytes,2,opt,name=moiTable,proto3" json:"moiTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MOITableInsertRequest) Reset()         { *m = MOITableInsertRequest{} }
func (m *MOITableInsertRequest) String() string { return proto.CompactTextString(m) }
func (*MOITableInsertRequest) ProtoMessage()    {}
func (*MOITableInsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{1}
}
func (m *MOITableInsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableInsertRequest.Unmarshal(m, b)
}
func (m *MOITableInsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableInsertRequest.Marshal(b, m, deterministic)
}
func (dst *MOITableInsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableInsertRequest.Merge(dst, src)
}
func (m *MOITableInsertRequest) XXX_Size() int {
	return xxx_messageInfo_MOITableInsertRequest.Size(m)
}
func (m *MOITableInsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableInsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableInsertRequest proto.InternalMessageInfo

func (m *MOITableInsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableInsertRequest) GetMoiTable() *MOITable {
	if m != nil {
		return m.MoiTable
	}
	return nil
}

// Contains data of created moi table
type MOITableInsertResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// SubId of created task
	XappID               uint32   `protobuf:"varint,2,opt,name=XappID,proto3" json:"XappID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableInsertResponse) Reset()         { *m = MOITableInsertResponse{} }
func (m *MOITableInsertResponse) String() string { return proto.CompactTextString(m) }
func (*MOITableInsertResponse) ProtoMessage()    {}
func (*MOITableInsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{2}
}
func (m *MOITableInsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableInsertResponse.Unmarshal(m, b)
}
func (m *MOITableInsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableInsertResponse.Marshal(b, m, deterministic)
}
func (dst *MOITableInsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableInsertResponse.Merge(dst, src)
}
func (m *MOITableInsertResponse) XXX_Size() int {
	return xxx_messageInfo_MOITableInsertResponse.Size(m)
}
func (m *MOITableInsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableInsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableInsertResponse proto.InternalMessageInfo

func (m *MOITableInsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableInsertResponse) GetXappID() uint32 {
	if m != nil {
		return m.XappID
	}
	return 0
}

// Request data to read moi table
type MOITableReadRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Unique integer identifier of the moi table
	XappID               uint32   `protobuf:"varint,2,opt,name=XappID,proto3" json:"XappID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableReadRequest) Reset()         { *m = MOITableReadRequest{} }
func (m *MOITableReadRequest) String() string { return proto.CompactTextString(m) }
func (*MOITableReadRequest) ProtoMessage()    {}
func (*MOITableReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{3}
}
func (m *MOITableReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableReadRequest.Unmarshal(m, b)
}
func (m *MOITableReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableReadRequest.Marshal(b, m, deterministic)
}
func (dst *MOITableReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableReadRequest.Merge(dst, src)
}
func (m *MOITableReadRequest) XXX_Size() int {
	return xxx_messageInfo_MOITableReadRequest.Size(m)
}
func (m *MOITableReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableReadRequest proto.InternalMessageInfo

func (m *MOITableReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableReadRequest) GetXappID() uint32 {
	if m != nil {
		return m.XappID
	}
	return 0
}

// Contains moi table data specified in by ID request
type MOITableReadResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Task entity read by SubIdXapp
	MoiTable             *MOITable `protobuf:"bytes,2,opt,name=moiTable,proto3" json:"moiTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MOITableReadResponse) Reset()         { *m = MOITableReadResponse{} }
func (m *MOITableReadResponse) String() string { return proto.CompactTextString(m) }
func (*MOITableReadResponse) ProtoMessage()    {}
func (*MOITableReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{4}
}
func (m *MOITableReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableReadResponse.Unmarshal(m, b)
}
func (m *MOITableReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableReadResponse.Marshal(b, m, deterministic)
}
func (dst *MOITableReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableReadResponse.Merge(dst, src)
}
func (m *MOITableReadResponse) XXX_Size() int {
	return xxx_messageInfo_MOITableReadResponse.Size(m)
}
func (m *MOITableReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableReadResponse proto.InternalMessageInfo

func (m *MOITableReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableReadResponse) GetMoiTable() *MOITable {
	if m != nil {
		return m.MoiTable
	}
	return nil
}

// Request data to update moi table
type MOITableUpdateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Task entity to update
	MoiTable             *MOITable `protobuf:"bytes,2,opt,name=moiTable,proto3" json:"moiTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MOITableUpdateRequest) Reset()         { *m = MOITableUpdateRequest{} }
func (m *MOITableUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MOITableUpdateRequest) ProtoMessage()    {}
func (*MOITableUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{5}
}
func (m *MOITableUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableUpdateRequest.Unmarshal(m, b)
}
func (m *MOITableUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *MOITableUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableUpdateRequest.Merge(dst, src)
}
func (m *MOITableUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MOITableUpdateRequest.Size(m)
}
func (m *MOITableUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableUpdateRequest proto.InternalMessageInfo

func (m *MOITableUpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableUpdateRequest) GetMoiTable() *MOITable {
	if m != nil {
		return m.MoiTable
	}
	return nil
}

// Contains status of update operation
type MOITableUpdateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Contains number of entities have beed updated
	// Equals 1 in case of succesfull update
	Updated              int32    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableUpdateResponse) Reset()         { *m = MOITableUpdateResponse{} }
func (m *MOITableUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MOITableUpdateResponse) ProtoMessage()    {}
func (*MOITableUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{6}
}
func (m *MOITableUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableUpdateResponse.Unmarshal(m, b)
}
func (m *MOITableUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *MOITableUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableUpdateResponse.Merge(dst, src)
}
func (m *MOITableUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MOITableUpdateResponse.Size(m)
}
func (m *MOITableUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableUpdateResponse proto.InternalMessageInfo

func (m *MOITableUpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableUpdateResponse) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

// Request data to delete moi table
type MOITableDeleteRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Unique integer identifier of the moi table to delete
	XappID               uint32   `protobuf:"varint,2,opt,name=XappID,proto3" json:"XappID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableDeleteRequest) Reset()         { *m = MOITableDeleteRequest{} }
func (m *MOITableDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*MOITableDeleteRequest) ProtoMessage()    {}
func (*MOITableDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{7}
}
func (m *MOITableDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableDeleteRequest.Unmarshal(m, b)
}
func (m *MOITableDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *MOITableDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableDeleteRequest.Merge(dst, src)
}
func (m *MOITableDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_MOITableDeleteRequest.Size(m)
}
func (m *MOITableDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableDeleteRequest proto.InternalMessageInfo

func (m *MOITableDeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableDeleteRequest) GetXappID() uint32 {
	if m != nil {
		return m.XappID
	}
	return 0
}

// Contains status of delete operation
type MOITableDeleteResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Contains number of entities have beed deleted
	// Equals 1 in case of succesfull delete
	Deleted              int32    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableDeleteResponse) Reset()         { *m = MOITableDeleteResponse{} }
func (m *MOITableDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*MOITableDeleteResponse) ProtoMessage()    {}
func (*MOITableDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{8}
}
func (m *MOITableDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableDeleteResponse.Unmarshal(m, b)
}
func (m *MOITableDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *MOITableDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableDeleteResponse.Merge(dst, src)
}
func (m *MOITableDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_MOITableDeleteResponse.Size(m)
}
func (m *MOITableDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableDeleteResponse proto.InternalMessageInfo

func (m *MOITableDeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableDeleteResponse) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

// Request data to read all moi table
type MOITableReadAllRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MOITableReadAllRequest) Reset()         { *m = MOITableReadAllRequest{} }
func (m *MOITableReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*MOITableReadAllRequest) ProtoMessage()    {}
func (*MOITableReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{9}
}
func (m *MOITableReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableReadAllRequest.Unmarshal(m, b)
}
func (m *MOITableReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableReadAllRequest.Marshal(b, m, deterministic)
}
func (dst *MOITableReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableReadAllRequest.Merge(dst, src)
}
func (m *MOITableReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_MOITableReadAllRequest.Size(m)
}
func (m *MOITableReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableReadAllRequest proto.InternalMessageInfo

func (m *MOITableReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// Contains list of all moi tables
type MOITableReadAllResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// List of all moi tables
	MoiTables            []*MOITable `protobuf:"bytes,2,rep,name=moiTables,proto3" json:"moiTables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MOITableReadAllResponse) Reset()         { *m = MOITableReadAllResponse{} }
func (m *MOITableReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*MOITableReadAllResponse) ProtoMessage()    {}
func (*MOITableReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_moitable_e21c3ec5a4e63fff, []int{10}
}
func (m *MOITableReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MOITableReadAllResponse.Unmarshal(m, b)
}
func (m *MOITableReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MOITableReadAllResponse.Marshal(b, m, deterministic)
}
func (dst *MOITableReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MOITableReadAllResponse.Merge(dst, src)
}
func (m *MOITableReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_MOITableReadAllResponse.Size(m)
}
func (m *MOITableReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MOITableReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MOITableReadAllResponse proto.InternalMessageInfo

func (m *MOITableReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MOITableReadAllResponse) GetMoiTables() []*MOITable {
	if m != nil {
		return m.MoiTables
	}
	return nil
}

func init() {
	proto.RegisterType((*MOITable)(nil), "db.MOITable")
	proto.RegisterType((*MOITableInsertRequest)(nil), "db.MOITableInsertRequest")
	proto.RegisterType((*MOITableInsertResponse)(nil), "db.MOITableInsertResponse")
	proto.RegisterType((*MOITableReadRequest)(nil), "db.MOITableReadRequest")
	proto.RegisterType((*MOITableReadResponse)(nil), "db.MOITableReadResponse")
	proto.RegisterType((*MOITableUpdateRequest)(nil), "db.MOITableUpdateRequest")
	proto.RegisterType((*MOITableUpdateResponse)(nil), "db.MOITableUpdateResponse")
	proto.RegisterType((*MOITableDeleteRequest)(nil), "db.MOITableDeleteRequest")
	proto.RegisterType((*MOITableDeleteResponse)(nil), "db.MOITableDeleteResponse")
	proto.RegisterType((*MOITableReadAllRequest)(nil), "db.MOITableReadAllRequest")
	proto.RegisterType((*MOITableReadAllResponse)(nil), "db.MOITableReadAllResponse")
}

func init() { proto.RegisterFile("moitable.proto", fileDescriptor_moitable_e21c3ec5a4e63fff) }

var fileDescriptor_moitable_e21c3ec5a4e63fff = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x6b, 0xdb, 0x30,
	0x18, 0xc6, 0xb1, 0xd3, 0x24, 0xce, 0xdb, 0x75, 0x0c, 0xad, 0xeb, 0x44, 0x18, 0xcc, 0x98, 0x1d,
	0x4c, 0x0f, 0x2e, 0x74, 0xb0, 0xcb, 0x0e, 0xa3, 0x25, 0x0c, 0x72, 0xd8, 0x06, 0x6a, 0xf6, 0x87,
	0xdd, 0xe4, 0xea, 0x5d, 0x10, 0xd8, 0x92, 0x66, 0xc9, 0x87, 0xdd, 0xf7, 0xc1, 0x87, 0x95, 0xca,
	0x4e, 0xd7, 0xb9, 0xec, 0xd0, 0x9b, 0x9e, 0xf7, 0x7d, 0xf4, 0xe8, 0xf1, 0x0f, 0xc3, 0xe3, 0x5a,
	0x4b, 0xc7, 0xcb, 0x0a, 0x0b, 0xd3, 0x68, 0xa7, 0x49, 0x2c, 0xca, 0xe5, 0xcb, 0xad, 0xd6, 0xdb,
	0x0a, 0xcf, 0xfc, 0xa4, 0x6c, 0x7f, 0x9c, 0x39, 0x59, 0xa3, 0x75, 0xbc, 0x36, 0x3b, 0x53, 0xf6,
	0x3b, 0x86, 0xe4, 0xc3, 0xa7, 0xf5, 0xa6, 0xbb, 0x47, 0x4e, 0x60, 0xf6, 0x8d, 0x1b, 0xb3, 0x5e,
	0xd1, 0x28, 0x8d, 0xf2, 0x23, 0x76, 0xa3, 0x08, 0x85, 0x79, 0x77, 0xfa, 0x82, 0x0d, 0x8d, 0xd3,
	0x28, 0x8f, 0x59, 0x90, 0x64, 0x09, 0x49, 0x77, 0xfc, 0xc8, 0x6b, 0xa4, 0x93, 0x34, 0xca, 0x17,
	0xac, 0xd7, 0xe4, 0x05, 0x2c, 0xde, 0xb7, 0xea, 0xda, 0x49, 0xad, 0x2c, 0x3d, 0xf0, 0xcb, 0x61,
	0x40, 0x5e, 0xc1, 0x11, 0x6b, 0x95, 0x92, 0x6a, 0x7b, 0xe5, 0xb8, 0x6b, 0x2d, 0x9d, 0x7a, 0xc7,
	0xed, 0x61, 0xf7, 0xf2, 0xda, 0x32, 0xe4, 0xe2, 0x17, 0x9d, 0xf9, 0x7d, 0x90, 0xe4, 0x18, 0xa6,
	0x1b, 0x6d, 0xe4, 0x35, 0x9d, 0xfb, 0xf9, 0x4e, 0x90, 0x37, 0x90, 0x34, 0x58, 0x4b, 0x25, 0xb0,
	0xa1, 0x49, 0x1a, 0xe5, 0x87, 0xe7, 0xcb, 0x62, 0x87, 0xa0, 0x08, 0x08, 0x8a, 0x4d, 0x40, 0xc0,
	0x7a, 0x6f, 0x76, 0x05, 0xcf, 0x02, 0x85, 0xb5, 0xb2, 0xd8, 0x38, 0x86, 0x3f, 0x5b, 0xb4, 0x8e,
	0x3c, 0x81, 0x09, 0x37, 0xd2, 0xf3, 0x58, 0xb0, 0xee, 0x48, 0x72, 0x48, 0x6a, 0x2d, 0xbd, 0xd5,
	0xd3, 0x38, 0x3c, 0x7f, 0x54, 0x88, 0xb2, 0x08, 0xd7, 0x59, 0xbf, 0xcd, 0x2e, 0xe1, 0xe4, 0xef,
	0x50, 0x6b, 0xb4, 0xb2, 0xf8, 0x8f, 0xd4, 0x01, 0x7d, 0xbc, 0x8f, 0x3e, 0x7b, 0x07, 0x4f, 0xfb,
	0x64, 0xe4, 0x62, 0xbc, 0xd6, 0x58, 0x00, 0x83, 0xe3, 0xdb, 0x01, 0xa3, 0x15, 0xfe, 0xff, 0xc3,
	0xf6, 0x68, 0x7d, 0x36, 0x82, 0x3b, 0x7c, 0x08, 0x5a, 0xab, 0x81, 0x56, 0x08, 0x1d, 0xad, 0x4a,
	0x61, 0xde, 0x7a, 0x8f, 0xf0, 0xa1, 0x53, 0x16, 0x64, 0x76, 0x31, 0x54, 0x5b, 0x61, 0x85, 0xf7,
	0x55, 0x1b, 0x23, 0xb6, 0x57, 0x24, 0x44, 0xdc, 0x57, 0x44, 0x78, 0x4f, 0x5f, 0xe4, 0x46, 0x66,
	0xa7, 0x43, 0x4a, 0xc7, 0xfd, 0xa2, 0xaa, 0x46, 0x9b, 0x64, 0x5f, 0xe1, 0xf9, 0x1d, 0xef, 0xe8,
	0x93, 0xa7, 0xb0, 0x08, 0xcc, 0x2c, 0x8d, 0xd3, 0xc9, 0x1d, 0xa4, 0xc3, 0xfa, 0x72, 0xf6, 0xfd,
	0xa0, 0x78, 0x2b, 0xca, 0x72, 0xe6, 0x7f, 0xfe, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x2c, 0xee, 0x49, 0x23, 0x04, 0x00, 0x00,
}
