
package xapp
// #cgo CFLAGS: -I../../internal/asn1codec/ -DASN_DISABLE_OER_SUPPORT
// #cgo LDFLAGS: -L../../internal/asn1codec/   -lasn1objects
/*
#include <RIC_message_types.h>
*/
import "C"

//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
var RICMessageTypes = map[string]int{
	"RIC_HEALTH_CHECK_REQ":                C.RIC_HEALTH_CHECK_REQ,
	"RIC_HEALTH_CHECK_RESP":               C.RIC_HEALTH_CHECK_RESP,
	"RIC_SCTP_CONNECTION_FAILURE":         C.RIC_SCTP_CONNECTION_FAILURE,
	"RIC_SCTP_CLEAR_ALL":                  C.RIC_SCTP_CLEAR_ALL,
	"E2_TERM_INIT":                        C.E2_TERM_INIT,
	"E2_TERM_KEEP_ALIVE_REQ":              C.E2_TERM_KEEP_ALIVE_REQ,
	"E2_TERM_KEEP_ALIVE_RESP":             C.E2_TERM_KEEP_ALIVE_RESP,
	"RAN_CONNECTED":                       C.RAN_CONNECTED,
	"RAN_RESTARTED":                       C.RAN_RESTARTED,
	"RAN_RECONFIGURED":                    C.RAN_RECONFIGURED,
	"RIC_SUB_REQ":                         C.RIC_SUB_REQ,
	"RIC_SUB_RESP":                        C.RIC_SUB_RESP,
	"RIC_SUB_FAILURE":                     C.RIC_SUB_FAILURE,
	"RIC_SUB_DEL_REQ":                     C.RIC_SUB_DEL_REQ,
	"RIC_SUB_DEL_RESP":                    C.RIC_SUB_DEL_RESP,
	"RIC_SUB_DEL_FAILURE":                 C.RIC_SUB_DEL_FAILURE,
	"RIC_SERVICE_UPDATE":                  C.RIC_SERVICE_UPDATE,
	"RIC_SERVICE_UPDATE_ACK":              C.RIC_SERVICE_UPDATE_ACK,
	"RIC_SERVICE_UPDATE_FAILURE":          C.RIC_SERVICE_UPDATE_FAILURE,
	"RIC_CONTROL_REQ":                     C.RIC_CONTROL_REQ,
	"RIC_CONTROL_ACK":                     C.RIC_CONTROL_ACK,
	"RIC_CONTROL_FAILURE":                 C.RIC_CONTROL_FAILURE,
	"RIC_INDICATION":                      C.RIC_INDICATION,
	"RIC_SERVICE_QUERY":                   C.RIC_SERVICE_QUERY,
	"RIC_ENDC_X2_SETUP_REQ":               C.RIC_ENDC_X2_SETUP_REQ,
	"RIC_ENDC_X2_SETUP_RESP":              C.RIC_ENDC_X2_SETUP_RESP,
	"RIC_ENDC_X2_SETUP_FAILURE":           C.RIC_ENDC_X2_SETUP_FAILURE,
	"RIC_ENDC_CONF_UPDATE":                C.RIC_ENDC_CONF_UPDATE,
	"RIC_ENDC_CONF_UPDATE_ACK":            C.RIC_ENDC_CONF_UPDATE_ACK,
	"RIC_ENDC_CONF_UPDATE_FAILURE":        C.RIC_ENDC_CONF_UPDATE_FAILURE,
	"RIC_RES_STATUS_REQ":                  C.RIC_RES_STATUS_REQ,
	"RIC_RES_STATUS_RESP":                 C.RIC_RES_STATUS_RESP,
	"RIC_RES_STATUS_FAILURE":              C.RIC_RES_STATUS_FAILURE,
	"RIC_ENB_CONF_UPDATE":                 C.RIC_ENB_CONF_UPDATE,
	"RIC_ENB_CONF_UPDATE_ACK":             C.RIC_ENB_CONF_UPDATE_ACK,
	"RIC_ENB_CONF_UPDATE_FAILURE":         C.RIC_ENB_CONF_UPDATE_FAILURE,
	"RIC_ENB_LOAD_INFORMATION":            C.RIC_ENB_LOAD_INFORMATION,
	"RIC_GNB_STATUS_INDICATION":           C.RIC_GNB_STATUS_INDICATION,
	"RIC_RESOURCE_STATUS_UPDATE":          C.RIC_RESOURCE_STATUS_UPDATE,
	"RIC_ERROR_INDICATION":                C.RIC_ERROR_INDICATION,
	"RIC_SGNB_ADDITION_REQ":               C.RIC_SGNB_ADDITION_REQ,
	"RIC_SGNB_ADDITION_ACK":               C.RIC_SGNB_ADDITION_ACK,
	"RIC_SGNB_ADDITION_REJECT":            C.RIC_SGNB_ADDITION_REJECT,
	"RIC_SGNB_MOD_REQUEST":                C.RIC_SGNB_MOD_REQUEST,
	"RIC_SGNB_MOD_REQUEST_ACK":            C.RIC_SGNB_MOD_REQUEST_ACK,
	"RIC_SGNB_MOD_REQUEST_REJECT":         C.RIC_SGNB_MOD_REQUEST_REJ,
	"RIC_SGNB_MOD_REQUIRED":               C.RIC_SGNB_MOD_REQUIRED,
	"RIC_SGNB_MOD_CONFIRM":                C.RIC_SGNB_MOD_CONFIRM,
	"RIC_SGNB_MOD_REFUSE":                 C.RIC_SGNB_MOD_REFUSE,
	"RIC_SGNB_RELEASE_REQUEST":            C.RIC_SGNB_RELEASE_REQUEST,
	"RIC_SGNB_RELEASE_CONFIRM":            C.RIC_SGNB_RELEASE_CONFIRM,
	"RIC_SGNB_RELEASE_REQUIRED":           C.RIC_SGNB_RELEASE_REQUIRED,
	"RIC_SGNB_RELEASE_REQUEST_ACK":        C.RIC_SGNB_RELEASE_REQUEST_ACK,
	"RIC_SECONDARY_RAT_DATA_USAGE_REPORT": C.RIC_SECONDARY_RAT_DATA_USAGE_REPORT,
	"RIC_SN_STATUS_TRANSFER":              C.RIC_SN_STATUS_TRANSFER,
	"RIC_SGNB_RECONF_COMPLETE":            C.RIC_SGNB_RECONF_COMPLETE,
	"RIC_RRC_TRANSFER":                    C.RIC_RRC_TRANSFER,
	"RIC_UE_CONTEXT_RELEASE":              C.RIC_UE_CONTEXT_RELEASE,
	"A1_POLICY_REQ":                       C.A1_POLICY_REQ,
	"A1_POLICY_RESP":                      C.A1_POLICY_RESP,
	"A1_POLICY_QUERY":                     C.A1_POLICY_QUERY,
	"RIC_E2_TERMINATION_HC_REQUEST":       C.RIC_E2_TERMINATION_HC_REQUEST,
	"RIC_E2_TERMINATION_HC_RESPONSE":      C.RIC_E2_TERMINATION_HC_RESPONSE,
	"RIC_E2_MANAGER_HC_REQUEST":           C.RIC_E2_MANAGER_HC_REQUEST,
	"RIC_E2_MANAGER_HC_RESPONSE":          C.RIC_E2_MANAGER_HC_RESPONSE,
	"RIC_CONTROL_XAPP_CONFIG_REQUEST":     C.RIC_CONTROL_XAPP_CONFIG_REQUEST,
	"RIC_CONTROL_XAPP_CONFIG_RESPONSE":    C.RIC_CONTROL_XAPP_CONFIG_RESPONSE,
	"RIC_E2_SETUP_REQ":                    C.RIC_E2_SETUP_REQ,
	"RIC_E2_SETUP_RESP":                   C.RIC_E2_SETUP_RESP,
	"RIC_E2_SETUP_FAILURE":                C.RIC_E2_SETUP_FAILURE,
	"MC_REPORT":                           C.MC_REPORT,
	"RIC_ROUTE_INSERT":					   80000,
	"RIC_ROUTE_UPDATE":					   80001,

	"RIC_REGISTER_REQ":					   81000,
	"RIC_REGISTER_RESP":				   81001,
	"RIC_REGISTER_FAILURE":				   81002,
	"RIC_INIT_REQ":					 	   81003,
	"RIC_INIT_RESP":				  	   81004,
	"RIC_INIT_FAILURE":					   81005,
	"RIC_ENABLE_REQ":				   	   81006,
	"RIC_ENABLE_RESP":				   	   81007,
	"RIC_ENABLE_FAILURE":				   81008,
	//"RIC_DISABLE_REQ":				   81009,
	//"RIC_DISABLE_RESP":				   81010,
	//"RIC_DISABLE_FAILURE":			   81011,
	"RIC_DEREGISTER_REQ":			       81012,
	"RIC_DEREGISTER_RESP":				   81013,
	"RIC_DEREGISTER_FAILURE":			   81014,

	"RIC_O1_REGISTER_REPORT_REQ":		   91000,
	"RIC_O1_REGISTER_REPORT_RESP":		   91001,
	"RIC_O1_REGISTER_REPORT_FAILURE":	   91002,
	"RIC_O1_INIT_REQ":					   91003,
	"RIC_O1_INIT_RESP":				  	   91004,
	"RIC_O1_INIT_FAILURE":				   91005,
	"RIC_O1_ENABLE_REQ":				   91006,
	"RIC_O1_ENABLE_RESP":				   91007,
	"RIC_O1_ENABLE_FAILURE":			   91008,
	//"RIC_O1_DISABLE_REQ":				   91009,
	//"RIC_O1_DISABLE_RESP":			   91010,
	//"RIC_O1_DISABLE_FAILURE":			   91011,
	"RIC_O1_DEREGISTER_REQ":			   91012,
	"RIC_O1_DEREGISTER_RESP":			   91013,
	"RIC_O1_DEREGISTER_FAILURE":		   91014,
}


//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
const (
	RIC_HEALTH_CHECK_REQ                = C.RIC_HEALTH_CHECK_REQ
	RIC_HEALTH_CHECK_RESP               = C.RIC_HEALTH_CHECK_RESP
	RIC_SCTP_CONNECTION_FAILURE         = C.RIC_SCTP_CONNECTION_FAILURE
	RIC_SCTP_CLEAR_ALL                  = C.RIC_SCTP_CLEAR_ALL
	E2_TERM_INIT                        = C.E2_TERM_INIT
	E2_TERM_KEEP_ALIVE_REQ              = C.E2_TERM_KEEP_ALIVE_REQ
	E2_TERM_KEEP_ALIVE_RESP             = C.E2_TERM_KEEP_ALIVE_RESP
	RAN_CONNECTED                       = C.RAN_CONNECTED
	RAN_RESTARTED                       = C.RAN_RESTARTED
	RAN_RECONFIGURED                    = C.RAN_RECONFIGURED
	RIC_SUB_REQ                         = C.RIC_SUB_REQ
	RIC_SUB_RESP                        = C.RIC_SUB_RESP
	RIC_SUB_FAILURE                     = C.RIC_SUB_FAILURE
	RIC_SUB_DEL_REQ                     = C.RIC_SUB_DEL_REQ
	RIC_SUB_DEL_RESP                    = C.RIC_SUB_DEL_RESP
	RIC_SUB_DEL_FAILURE                 = C.RIC_SUB_DEL_FAILURE
	RIC_SERVICE_UPDATE                  = C.RIC_SERVICE_UPDATE
	RIC_SERVICE_UPDATE_ACK              = C.RIC_SERVICE_UPDATE_ACK
	RIC_SERVICE_UPDATE_FAILURE          = C.RIC_SERVICE_UPDATE_FAILURE
	RIC_CONTROL_REQ                     = C.RIC_CONTROL_REQ
	RIC_CONTROL_ACK                     = C.RIC_CONTROL_ACK
	RIC_CONTROL_FAILURE                 = C.RIC_CONTROL_FAILURE
	RIC_INDICATION                      = C.RIC_INDICATION
	RIC_SERVICE_QUERY                   = C.RIC_SERVICE_QUERY
	RIC_ENDC_X2_SETUP_REQ               = C.RIC_ENDC_X2_SETUP_REQ
	RIC_ENDC_X2_SETUP_RESP              = C.RIC_ENDC_X2_SETUP_RESP
	RIC_ENDC_X2_SETUP_FAILURE           = C.RIC_ENDC_X2_SETUP_FAILURE
	RIC_ENDC_CONF_UPDATE                = C.RIC_ENDC_CONF_UPDATE
	RIC_ENDC_CONF_UPDATE_ACK            = C.RIC_ENDC_CONF_UPDATE_ACK
	RIC_ENDC_CONF_UPDATE_FAILURE        = C.RIC_ENDC_CONF_UPDATE_FAILURE
	RIC_RES_STATUS_REQ                  = C.RIC_RES_STATUS_REQ
	RIC_RES_STATUS_RESP                 = C.RIC_RES_STATUS_RESP
	RIC_RES_STATUS_FAILURE              = C.RIC_RES_STATUS_FAILURE
	RIC_ENB_CONF_UPDATE                 = C.RIC_ENB_CONF_UPDATE
	RIC_ENB_CONF_UPDATE_ACK             = C.RIC_ENB_CONF_UPDATE_ACK
	RIC_ENB_CONF_UPDATE_FAILURE         = C.RIC_ENB_CONF_UPDATE_FAILURE
	RIC_ENB_LOAD_INFORMATION            = C.RIC_ENB_LOAD_INFORMATION
	RIC_GNB_STATUS_INDICATION           = C.RIC_GNB_STATUS_INDICATION
	RIC_RESOURCE_STATUS_UPDATE          = C.RIC_RESOURCE_STATUS_UPDATE
	RIC_ERROR_INDICATION                = C.RIC_ERROR_INDICATION
	RIC_SGNB_ADDITION_REQ               = C.RIC_SGNB_ADDITION_REQ
	RIC_SGNB_ADDITION_ACK               = C.RIC_SGNB_ADDITION_ACK
	RIC_SGNB_ADDITION_REJECT            = C.RIC_SGNB_ADDITION_REJECT
	RIC_SGNB_MOD_REQUEST                = C.RIC_SGNB_MOD_REQUEST
	RIC_SGNB_MOD_REQUEST_ACK            = C.RIC_SGNB_MOD_REQUEST_ACK
	RIC_SGNB_MOD_REQUEST_REJECT         = C.RIC_SGNB_MOD_REQUEST_REJ
	RIC_SGNB_MOD_REQUIRED               = C.RIC_SGNB_MOD_REQUIRED
	RIC_SGNB_MOD_CONFIRM                = C.RIC_SGNB_MOD_CONFIRM
	RIC_SGNB_MOD_REFUSE                 = C.RIC_SGNB_MOD_REFUSE
	RIC_SGNB_RELEASE_REQUEST            = C.RIC_SGNB_RELEASE_REQUEST
	RIC_SGNB_RELEASE_CONFIRM            = C.RIC_SGNB_RELEASE_CONFIRM
	RIC_SGNB_RELEASE_REQUIRED           = C.RIC_SGNB_RELEASE_REQUIRED
	RIC_SGNB_RELEASE_REQUEST_ACK        = C.RIC_SGNB_RELEASE_REQUEST_ACK
	RIC_SECONDARY_RAT_DATA_USAGE_REPORT = C.RIC_SECONDARY_RAT_DATA_USAGE_REPORT
	RIC_SN_STATUS_TRANSFER              = C.RIC_SN_STATUS_TRANSFER
	RIC_SGNB_RECONF_COMPLETE            = C.RIC_SGNB_RECONF_COMPLETE
	RIC_RRC_TRANSFER                    = C.RIC_RRC_TRANSFER
	RIC_UE_CONTEXT_RELEASE              = C.RIC_UE_CONTEXT_RELEASE
	A1_POLICY_REQ                       = C.A1_POLICY_REQ
	A1_POLICY_RESP                      = C.A1_POLICY_RESP
	A1_POLICY_QUERY                     = C.A1_POLICY_QUERY
	RIC_E2_TERMINATION_HC_REQUEST       = C.RIC_E2_TERMINATION_HC_REQUEST
	RIC_E2_TERMINATION_HC_RESPONSE      = C.RIC_E2_TERMINATION_HC_RESPONSE
	RIC_E2_MANAGER_HC_REQUEST           = C.RIC_E2_MANAGER_HC_REQUEST
	RIC_E2_MANAGER_HC_RESPONSE          = C.RIC_E2_MANAGER_HC_RESPONSE
	RIC_CONTROL_XAPP_CONFIG_REQUEST     = C.RIC_CONTROL_XAPP_CONFIG_REQUEST
	RIC_CONTROL_XAPP_CONFIG_RESPONSE    = C.RIC_CONTROL_XAPP_CONFIG_RESPONSE
	RIC_E2_SETUP_REQ                    = C.RIC_E2_SETUP_REQ
	RIC_E2_SETUP_RESP                   = C.RIC_E2_SETUP_RESP
	RIC_E2_SETUP_FAILURE                = C.RIC_E2_SETUP_FAILURE
	MC_REPORT                           = C.MC_REPORT
	RIC_ROUTE_INSERT                    = 80000
	RIC_ROUTE_UPDATE				    = 80001

	RIC_REGISTER_REQ					= 81000
	RIC_REGISTER_RESP					= 81001
	RIC_REGISTER_FAILURE				= 81002
	RIC_INIT_REQ						= 81003
	RIC_INIT_RESP						= 81004
	RIC_INIT_FAILURE					= 81005
	RIC_ENABLE_REQ						= 81006
	RIC_ENABLE_RESP						= 81007
	RIC_ENABLE_FAILURE					= 81008
	//RIC_DISABLE_REQ					= 81009
	//RIC_DISABLE_RESP					= 81010
	//RIC_DISABLE_FAILURE				= 81011
	RIC_DEREGISTER_REQ					= 81012
	RIC_DEREGISTER_RESP					= 81013
	RIC_DEREGISTER_FAILURE				= 81014

	RIC_O1_REGISTER_REPORT_REQ			= 91000
	RIC_O1_REGISTER_REPORT_RESP			= 91001
	RIC_O1_REGISTER_REPORT_FAILURE		= 91002
	RIC_O1_INIT_REQ						= 91003
	RIC_O1_INIT_RESP					= 91004
	RIC_O1_INIT_FAILURE					= 91005
	RIC_O1_ENABLE_REQ				    = 91006
	RIC_O1_ENABLE_RESP					= 91007
	RIC_O1_ENABLE_FAILURE				= 91008
	//RIC_O1_DISABLE_REQ				= 91009
	//RIC_O1_DISABLE_RESP				= 91010
	//RIC_O1_DISABLE_FAILURE			= 91011
	RIC_O1_DEREGISTER_REQ				= 91012
	RIC_O1_DEREGISTER_RESP				= 91013
	RIC_O1_DEREGISTER_FAILURE			= 91014
)



//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
var RicMessageTypeToName = map[int]string{
	RIC_HEALTH_CHECK_REQ:                "RIC_HEALTH_CHECK_REQ",
	RIC_HEALTH_CHECK_RESP:               "RIC_HEALTH_CHECK_RESP",
	RIC_SCTP_CONNECTION_FAILURE:         "RIC SCTP CONNECTION FAILURE",
	RIC_SCTP_CLEAR_ALL:                  "RIC SCTP CLEAR ALL",
	E2_TERM_INIT:                        "E2 TERM INIT",
	E2_TERM_KEEP_ALIVE_REQ:              "E2 TERM KEEP ALIVE REQ",
	E2_TERM_KEEP_ALIVE_RESP:             "E2 TERM KEEP ALIVE RESP",
	RAN_CONNECTED:                       "RAN CONNECTED",
	RAN_RESTARTED:                       "RAN RESTARTED",
	RAN_RECONFIGURED:                    "RAN RECONFIGURED",
	RIC_SUB_REQ:                         "RIC SUBSCRIPTION REQUEST",
	RIC_SUB_RESP:                        "RIC SUBSCRIPTION RESPONSE",
	RIC_SUB_FAILURE:                     "RIC SUBSCRIPTION FAILURE",
	RIC_SUB_DEL_REQ:                     "RIC SUBSCRIPTION DELETE REQUEST",
	RIC_SUB_DEL_RESP:                    "RIC SUBSCRIPTION DELETE RESPONSE",
	RIC_SUB_DEL_FAILURE:                 "RIC SUBSCRIPTION DELETE FAILURE",
	RIC_SERVICE_UPDATE:                  "RIC SERVICE UPDATE",
	RIC_SERVICE_UPDATE_ACK:              "RIC SERVICE UPDATE ACKNOWLEDGE",
	RIC_SERVICE_UPDATE_FAILURE:          "RIC SERVICE UPDATE FAILURE",
	RIC_CONTROL_REQ:                     "RIC CONTROL REQUEST",
	RIC_CONTROL_ACK:                     "RIC CONTROL ACKNOWLEDGE",
	RIC_CONTROL_FAILURE:                 "RIC CONTROL FAILURE",
	RIC_INDICATION:                      "RIC INDICATION",
	RIC_SERVICE_QUERY:                   "RIC SERVICE QUERY",
	RIC_ENDC_X2_SETUP_REQ:               "RIC EN-DC X2 SETUP REQUEST",
	RIC_ENDC_X2_SETUP_RESP:              "RIC EN-DC X2 SETUP RESPONSE",
	RIC_ENDC_X2_SETUP_FAILURE:           "RIC EN-DC X2 SETUP FAILURE",
	RIC_ENDC_CONF_UPDATE:                "RIC EN-DC CONFIGURATION UPDATE",
	RIC_ENDC_CONF_UPDATE_ACK:            "RIC EN-DC CONFIGURATION UPDATE ACKNOWLEDGE",
	RIC_ENDC_CONF_UPDATE_FAILURE:        "RIC EN-DC CONFIGURATION UPDATE FAILURE",
	RIC_RES_STATUS_REQ:                  "RIC RESOURCE STATUS REQUEST",
	RIC_RES_STATUS_RESP:                 "RIC RESOURCE STATUS RESPONSE",
	RIC_RES_STATUS_FAILURE:              "RIC RESOURCE STATUS FAILURE",
	RIC_ENB_CONF_UPDATE:                 "RIC ENB CONFIGURATION UPDATE",
	RIC_ENB_CONF_UPDATE_ACK:             "RIC ENB CONFIGURATION UPDATE ACKNOWLEDGE",
	RIC_ENB_CONF_UPDATE_FAILURE:         "RIC ENB CONFIGURATION UPDATE FAILURE",
	RIC_ENB_LOAD_INFORMATION:            "RIC ENB LOAD INFORMATION",
	RIC_GNB_STATUS_INDICATION:           "RIC GNB STATUS INDICATION",
	RIC_RESOURCE_STATUS_UPDATE:          "RIC RESOURCE STATUS UPDATE",
	RIC_ERROR_INDICATION:                "RIC ERROR INDICATION",
	RIC_SGNB_ADDITION_REQ:               "RIC SGNB ADDITION REQ",
	RIC_SGNB_ADDITION_ACK:               "RIC SGNB ADDITION ACK",
	RIC_SGNB_ADDITION_REJECT:            "RIC SGNB ADDITION REJECT",
	RIC_SGNB_MOD_REQUEST:                "RIC SGNB MOD REQUEST REQ",
	RIC_SGNB_MOD_REQUEST_ACK:            "RIC SGNB MOD REQUEST ACK",
	RIC_SGNB_MOD_REQUEST_REJECT:         "RIC SGNB MOD REQUEST REJ",
	RIC_SGNB_MOD_REQUIRED:               "RIC SGNB MOD REQUIRED",
	RIC_SGNB_MOD_CONFIRM:                "RIC SGNB MOD CONFIRM",
	RIC_SGNB_MOD_REFUSE:                 "RIC SGNB MOD REFUSE",
	RIC_SGNB_RELEASE_REQUEST:            "RIC SGNB RELEASE REQUEST",
	RIC_SGNB_RELEASE_CONFIRM:            "RIC SGNB RELEASE CONFIRM",
	RIC_SGNB_RELEASE_REQUIRED:           "RIC SGNB RELEASE REQUIRED",
	RIC_SGNB_RELEASE_REQUEST_ACK:        "RIC SGNB RELEASE REQUEST ACK",
	RIC_SECONDARY_RAT_DATA_USAGE_REPORT: "RIC SECONDARY RAT DATA USAGE REPORT",
	RIC_SN_STATUS_TRANSFER:              "RIC SN STATUS TRANSFER",
	RIC_SGNB_RECONF_COMPLETE:            "RIC SGNB RECONF COMPLETE",
	RIC_RRC_TRANSFER:                    "RIC RRC TRANSFER",
	RIC_UE_CONTEXT_RELEASE:              "RIC UE CONTEXT RELEASE",
	A1_POLICY_REQ:                       "A1_POLICY_REQ",
	A1_POLICY_RESP:                      "A1_POLICY_RESP",
	A1_POLICY_QUERY:                     "A1_POLICY_QUERY",
	RIC_E2_TERMINATION_HC_REQUEST:       "RIC_E2_TERMINATION_HC_REQUEST",
	RIC_E2_TERMINATION_HC_RESPONSE:      "RIC_E2_TERMINATION_HC_RESPONSE",
	RIC_E2_MANAGER_HC_REQUEST:           "RIC_E2_MANAGER_HC_REQUEST",
	RIC_E2_MANAGER_HC_RESPONSE:          "RIC_E2_MANAGER_HC_RESPONSE",
	RIC_CONTROL_XAPP_CONFIG_REQUEST:     "RIC_CONTROL_XAPP_CONFIG_REQUEST",
	RIC_CONTROL_XAPP_CONFIG_RESPONSE:    "RIC_CONTROL_XAPP_CONFIG_RESPONSE",
	RIC_E2_SETUP_REQ:                    "RIC_E2_SETUP_REQ",
	RIC_E2_SETUP_RESP:                   "RIC_E2_SETUP_RESP",
	RIC_E2_SETUP_FAILURE:                "RIC_E2_SETUP_FAILURE",
	MC_REPORT:                           "MC_REPORT",
	RIC_ROUTE_INSERT:					 "RIC_ROUTE_INSERT",
	RIC_ROUTE_UPDATE:					 "RIC_ROUTE_UPDATE",

	RIC_REGISTER_REQ:					 "RIC_REGISTER_REQ",
	RIC_REGISTER_RESP:					 "RIC_REGISTER_RESP",
	RIC_REGISTER_FAILURE:				 "RIC_REGISTER_FAILURE",
	RIC_INIT_REQ:						 "RIC_INIT_REQ",
	RIC_INIT_RESP:				 		 "RIC_INIT_RESP",
	RIC_INIT_FAILURE:					 "RIC_INIT_FAILURE",
	RIC_ENABLE_REQ:					 	 "RIC_ENABLE_REQ",
	RIC_ENABLE_RESP:				 	 "RIC_ENABLE_RESP",
	RIC_ENABLE_FAILURE:				 	 "RIC_ENABLE_FAILURE",
	//RIC_DISABLE_REQ:					 "RIC_DISABLE_REQ",
	//RIC_DISABLE_RESP:					 "RIC_DISABLE_RESP",
	//RIC_DISABLE_FAILURE:				 "RIC_DISABLE_FAILURE",
	RIC_DEREGISTER_REQ:					 "RIC_DEREGISTER_REQ",
	RIC_DEREGISTER_RESP:				 "RIC_DEREGISTER_RESP",

	RIC_DEREGISTER_FAILURE:				 "RIC_DEREGISTER_FAILURE",
	RIC_O1_REGISTER_REPORT_REQ:			 "RIC_O1_REGISTER_REPORT_REQ",
	RIC_O1_REGISTER_REPORT_RESP:		 "RIC_O1_REGISTER_REPORT_RESP",
	RIC_O1_REGISTER_REPORT_FAILURE:		 "RIC_O1_REGISTER_REPORT_FAILURE",
	RIC_O1_INIT_REQ:					 "RIC_O1_INIT_REQ",
	RIC_O1_INIT_RESP:				 	 "RIC_O1_INIT_RESP",
	RIC_O1_INIT_FAILURE:				 "RIC_O1_INIT_FAILURE",
	RIC_O1_ENABLE_REQ:					 "RIC_O1_ENABLE_REQ",
	RIC_O1_ENABLE_RESP:				 	 "RIC_O1_ENABLE_RESP",
	RIC_O1_ENABLE_FAILURE:				 "RIC_O1_ENABLE_FAILURE",
	//RIC_O1_DISABLE_REQ:					 "RIC_O1_DISABLE_REQ",
	//RIC_O1_DISABLE_RESP:				 "RIC_O1_DISABLE_RESP",
	//RIC_O1_DISABLE_FAILURE:				 "RIC_O1_DISABLE_FAILURE",
	RIC_O1_DEREGISTER_REQ:				 "RIC_O1_DEREGISTER_REQ",
	RIC_O1_DEREGISTER_RESP:				 "RIC_O1_DEREGISTER_RESP",
	RIC_O1_DEREGISTER_FAILURE:			 "RIC_O1_DEREGISTER_FAILURE",
}
