/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_A4EventTriggerConfiguration_H_
#define	_A4EventTriggerConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "NativeInteger.h"
#include "MeasurementTriggerQuantity.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum A4EventTriggerConfiguration__timeToTrigger {
	A4EventTriggerConfiguration__timeToTrigger_ms0	= 0,
	A4EventTriggerConfiguration__timeToTrigger_ms40	= 1,
	A4EventTriggerConfiguration__timeToTrigger_ms64	= 2,
	A4EventTriggerConfiguration__timeToTrigger_ms80	= 3,
	A4EventTriggerConfiguration__timeToTrigger_ms100	= 4,
	A4EventTriggerConfiguration__timeToTrigger_ms128	= 5,
	A4EventTriggerConfiguration__timeToTrigger_ms160	= 6,
	A4EventTriggerConfiguration__timeToTrigger_ms256	= 7,
	A4EventTriggerConfiguration__timeToTrigger_ms320	= 8,
	A4EventTriggerConfiguration__timeToTrigger_ms480	= 9,
	A4EventTriggerConfiguration__timeToTrigger_ms512	= 10,
	A4EventTriggerConfiguration__timeToTrigger_ms640	= 11,
	A4EventTriggerConfiguration__timeToTrigger_ms1024	= 12,
	A4EventTriggerConfiguration__timeToTrigger_ms1280	= 13,
	A4EventTriggerConfiguration__timeToTrigger_ms2560	= 14,
	A4EventTriggerConfiguration__timeToTrigger_ms5120	= 15
} e_A4EventTriggerConfiguration__timeToTrigger;
typedef enum A4EventTriggerConfiguration__referenceSignalType {
	A4EventTriggerConfiguration__referenceSignalType_ssb	= 0,
	A4EventTriggerConfiguration__referenceSignalType_csi_rs	= 1
} e_A4EventTriggerConfiguration__referenceSignalType;
typedef enum A4EventTriggerConfiguration__reportInterval {
	A4EventTriggerConfiguration__reportInterval_ms120	= 0,
	A4EventTriggerConfiguration__reportInterval_ms240	= 1,
	A4EventTriggerConfiguration__reportInterval_ms480	= 2,
	A4EventTriggerConfiguration__reportInterval_ms640	= 3,
	A4EventTriggerConfiguration__reportInterval_ms1024	= 4,
	A4EventTriggerConfiguration__reportInterval_ms2048	= 5,
	A4EventTriggerConfiguration__reportInterval_ms5120	= 6,
	A4EventTriggerConfiguration__reportInterval_ms10240	= 7,
	A4EventTriggerConfiguration__reportInterval_ms20480	= 8,
	A4EventTriggerConfiguration__reportInterval_ms40960	= 9,
	A4EventTriggerConfiguration__reportInterval_min1	= 10,
	A4EventTriggerConfiguration__reportInterval_min6	= 11,
	A4EventTriggerConfiguration__reportInterval_min12	= 12,
	A4EventTriggerConfiguration__reportInterval_min30	= 13
} e_A4EventTriggerConfiguration__reportInterval;
typedef enum A4EventTriggerConfiguration__reportAmount {
	A4EventTriggerConfiguration__reportAmount_r1	= 0,
	A4EventTriggerConfiguration__reportAmount_r2	= 1,
	A4EventTriggerConfiguration__reportAmount_r4	= 2,
	A4EventTriggerConfiguration__reportAmount_r8	= 3,
	A4EventTriggerConfiguration__reportAmount_r16	= 4,
	A4EventTriggerConfiguration__reportAmount_r32	= 5,
	A4EventTriggerConfiguration__reportAmount_r64	= 6,
	A4EventTriggerConfiguration__reportAmount_infinity	= 7
} e_A4EventTriggerConfiguration__reportAmount;

/* Forward declarations */
struct MeasurementTriggerQuantity;

/* A4EventTriggerConfiguration */
typedef struct A4EventTriggerConfiguration {
	BOOLEAN_t	 enable;
	long	 index;
	MeasurementTriggerQuantity_t	 a4Threshold;
	BOOLEAN_t	 reportOnLeave;
	long	 hysteresis;
	long	 timeToTrigger;
	BOOLEAN_t	 useWhiteCellList;
	long	 referenceSignalType;
	long	 reportInterval;
	long	 reportAmount;
	MeasurementTriggerQuantity_t	 reportQuantityCell;
	long	 maxReportCells;
	struct MeasurementTriggerQuantity	*reportQuantityRsIndex;	/* OPTIONAL */
	BOOLEAN_t	 includeBeamMeasurements;
	long	*maxNrOfRsIndexesToReport;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} A4EventTriggerConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_timeToTrigger_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_referenceSignalType_25;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_reportInterval_28;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_reportAmount_43;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_A4EventTriggerConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_A4EventTriggerConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_A4EventTriggerConfiguration_1[15];

#ifdef __cplusplus
}
#endif

#endif	/* _A4EventTriggerConfiguration_H_ */
#include "asn_internal.h"
