/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_AllocationandRetentionPriority_H_
#define	_AllocationandRetentionPriority_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AllocationandRetentionPriority__pre_emptionCapability {
	AllocationandRetentionPriority__pre_emptionCapability_shallnottriggerpre_emption	= 0,
	AllocationandRetentionPriority__pre_emptionCapability_maytriggerpre_emption	= 1
} e_AllocationandRetentionPriority__pre_emptionCapability;
typedef enum AllocationandRetentionPriority__pre_emptionVulnerability {
	AllocationandRetentionPriority__pre_emptionVulnerability_notpre_emptable	= 0,
	AllocationandRetentionPriority__pre_emptionVulnerability_pre_emptable	= 1
} e_AllocationandRetentionPriority__pre_emptionVulnerability;

/* AllocationandRetentionPriority */
typedef struct AllocationandRetentionPriority {
	long	 priorityLevel;
	long	 pre_emptionCapability;
	long	 pre_emptionVulnerability;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AllocationandRetentionPriority_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_pre_emptionCapability_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pre_emptionVulnerability_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_AllocationandRetentionPriority;
extern asn_SEQUENCE_specifics_t asn_SPC_AllocationandRetentionPriority_specs_1;
extern asn_TYPE_member_t asn_MBR_AllocationandRetentionPriority_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AllocationandRetentionPriority_H_ */
#include "asn_internal.h"
