/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_CommonCellReselectionConfiguration_H_
#define	_CommonCellReselectionConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ThresholdNR.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CommonCellReselectionConfiguration__rangeToBestCell {
	CommonCellReselectionConfiguration__rangeToBestCell_dB_24	= 0,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_22	= 1,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_20	= 2,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_18	= 3,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_16	= 4,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_14	= 5,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_12	= 6,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_10	= 7,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_8	= 8,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_6	= 9,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_5	= 10,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_4	= 11,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_3	= 12,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_2	= 13,
	CommonCellReselectionConfiguration__rangeToBestCell_dB_1	= 14,
	CommonCellReselectionConfiguration__rangeToBestCell_dB0	= 15,
	CommonCellReselectionConfiguration__rangeToBestCell_dB1	= 16,
	CommonCellReselectionConfiguration__rangeToBestCell_dB2	= 17,
	CommonCellReselectionConfiguration__rangeToBestCell_dB3	= 18,
	CommonCellReselectionConfiguration__rangeToBestCell_dB4	= 19,
	CommonCellReselectionConfiguration__rangeToBestCell_dB5	= 20,
	CommonCellReselectionConfiguration__rangeToBestCell_dB6	= 21,
	CommonCellReselectionConfiguration__rangeToBestCell_dB8	= 22,
	CommonCellReselectionConfiguration__rangeToBestCell_dB10	= 23,
	CommonCellReselectionConfiguration__rangeToBestCell_dB12	= 24,
	CommonCellReselectionConfiguration__rangeToBestCell_dB14	= 25,
	CommonCellReselectionConfiguration__rangeToBestCell_dB16	= 26,
	CommonCellReselectionConfiguration__rangeToBestCell_dB18	= 27,
	CommonCellReselectionConfiguration__rangeToBestCell_dB20	= 28,
	CommonCellReselectionConfiguration__rangeToBestCell_dB22	= 29,
	CommonCellReselectionConfiguration__rangeToBestCell_dB24	= 30
} e_CommonCellReselectionConfiguration__rangeToBestCell;
typedef enum CommonCellReselectionConfiguration__qhyst {
	CommonCellReselectionConfiguration__qhyst_dB0	= 0,
	CommonCellReselectionConfiguration__qhyst_dB1	= 1,
	CommonCellReselectionConfiguration__qhyst_dB2	= 2,
	CommonCellReselectionConfiguration__qhyst_dB3	= 3,
	CommonCellReselectionConfiguration__qhyst_dB4	= 4,
	CommonCellReselectionConfiguration__qhyst_dB5	= 5,
	CommonCellReselectionConfiguration__qhyst_dB6	= 6,
	CommonCellReselectionConfiguration__qhyst_dB8	= 7,
	CommonCellReselectionConfiguration__qhyst_dB10	= 8,
	CommonCellReselectionConfiguration__qhyst_dB12	= 9,
	CommonCellReselectionConfiguration__qhyst_dB14	= 10,
	CommonCellReselectionConfiguration__qhyst_dB16	= 11,
	CommonCellReselectionConfiguration__qhyst_dB18	= 12,
	CommonCellReselectionConfiguration__qhyst_dB20	= 13,
	CommonCellReselectionConfiguration__qhyst_dB22	= 14,
	CommonCellReselectionConfiguration__qhyst_dB24	= 15
} e_CommonCellReselectionConfiguration__qhyst;

/* Forward declarations */
struct SpeedStateReselectionPars;

/* CommonCellReselectionConfiguration */
typedef struct CommonCellReselectionConfiguration {
	long	*nrofSs_BlocksToAverage;	/* OPTIONAL */
	ThresholdNR_t	 absThreshSs_BlocksConsolidation;
	long	*rangeToBestCell;	/* OPTIONAL */
	long	 qhyst;
	struct SpeedStateReselectionPars	*speedStateReselectionPars;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommonCellReselectionConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rangeToBestCell_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_qhyst_36;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CommonCellReselectionConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_CommonCellReselectionConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_CommonCellReselectionConfiguration_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CommonCellReselectionConfiguration_H_ */
#include "asn_internal.h"
