/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ConfiguredGrantConfig_H_
#define	_ConfiguredGrantConfig_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfiguredGrantConfig__periodicity {
	ConfiguredGrantConfig__periodicity_sym2	= 0,
	ConfiguredGrantConfig__periodicity_sym7	= 1,
	ConfiguredGrantConfig__periodicity_sym1x14	= 2,
	ConfiguredGrantConfig__periodicity_sym2x14	= 3,
	ConfiguredGrantConfig__periodicity_sym4x14	= 4,
	ConfiguredGrantConfig__periodicity_sym5x14	= 5,
	ConfiguredGrantConfig__periodicity_sym8x14	= 6,
	ConfiguredGrantConfig__periodicity_sym10x14	= 7,
	ConfiguredGrantConfig__periodicity_sym16x14	= 8,
	ConfiguredGrantConfig__periodicity_sym20x14	= 9,
	ConfiguredGrantConfig__periodicity_sym32x14	= 10,
	ConfiguredGrantConfig__periodicity_sym40x14	= 11,
	ConfiguredGrantConfig__periodicity_sym64x14	= 12,
	ConfiguredGrantConfig__periodicity_sym80x14	= 13,
	ConfiguredGrantConfig__periodicity_sym128x14	= 14,
	ConfiguredGrantConfig__periodicity_sym160x14	= 15,
	ConfiguredGrantConfig__periodicity_sym256x14	= 16,
	ConfiguredGrantConfig__periodicity_sym320x14	= 17,
	ConfiguredGrantConfig__periodicity_sym512x14	= 18,
	ConfiguredGrantConfig__periodicity_sym640x14	= 19,
	ConfiguredGrantConfig__periodicity_sym1024x14	= 20,
	ConfiguredGrantConfig__periodicity_sym1280x14	= 21,
	ConfiguredGrantConfig__periodicity_sym2560x14	= 22,
	ConfiguredGrantConfig__periodicity_sym5120x14	= 23,
	ConfiguredGrantConfig__periodicity_sym6	= 24,
	ConfiguredGrantConfig__periodicity_sym1x12	= 25,
	ConfiguredGrantConfig__periodicity_sym2x12	= 26,
	ConfiguredGrantConfig__periodicity_sym4x12	= 27,
	ConfiguredGrantConfig__periodicity_sym5x12	= 28,
	ConfiguredGrantConfig__periodicity_sym8x12	= 29,
	ConfiguredGrantConfig__periodicity_sym10x12	= 30,
	ConfiguredGrantConfig__periodicity_sym16x12	= 31,
	ConfiguredGrantConfig__periodicity_sym20x12	= 32,
	ConfiguredGrantConfig__periodicity_sym32x12	= 33,
	ConfiguredGrantConfig__periodicity_sym40x12	= 34,
	ConfiguredGrantConfig__periodicity_sym64x12	= 35,
	ConfiguredGrantConfig__periodicity_sym80x12	= 36,
	ConfiguredGrantConfig__periodicity_sym128x12	= 37,
	ConfiguredGrantConfig__periodicity_sym160x12	= 38,
	ConfiguredGrantConfig__periodicity_sym256x12	= 39,
	ConfiguredGrantConfig__periodicity_sym320x12	= 40,
	ConfiguredGrantConfig__periodicity_sym512x12	= 41,
	ConfiguredGrantConfig__periodicity_sym640x12	= 42,
	ConfiguredGrantConfig__periodicity_sym1280x12	= 43,
	ConfiguredGrantConfig__periodicity_sym2560x12	= 44
} e_ConfiguredGrantConfig__periodicity;

/* ConfiguredGrantConfig */
typedef struct ConfiguredGrantConfig {
	long	*periodicity;	/* OPTIONAL */
	long	*configuredGrantTimer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfiguredGrantConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_periodicity_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ConfiguredGrantConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfiguredGrantConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfiguredGrantConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfiguredGrantConfig_H_ */
#include "asn_internal.h"
