/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_DRBQoSConfiguration_H_
#define	_DRBQoSConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DrbToBeSetup;

/* DRBQoSConfiguration */
typedef struct DRBQoSConfiguration {
	struct DRBQoSConfiguration__dRBToBeSetup_List {
		A_SEQUENCE_OF(struct DrbToBeSetup) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dRBToBeSetup_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBQoSConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBQoSConfiguration;

#ifdef __cplusplus
}
#endif

#endif	/* _DRBQoSConfiguration_H_ */
#include "asn_internal.h"
