/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_DRBQoS_H_
#define	_DRBQoS_H_


#include "asn_application.h"

/* Including external dependencies */
#include "QosCharacteristics-Choice.h"
#include "NativeInteger.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRBQoS__reflectiveQosAttribute {
	DRBQoS__reflectiveQosAttribute_subjectto	= 0
} e_DRBQoS__reflectiveQosAttribute;

/* Forward declarations */
struct GBRQoSFlowInformation;

/* DRBQoS */
typedef struct DRBQoS {
	QosCharacteristics_Choice_t	 qoSCharacteristics;
	long	*nG_RANAllocationAndRetentionPriority;	/* OPTIONAL */
	struct GBRQoSFlowInformation	*gBRQosFlowInformation;	/* OPTIONAL */
	long	*reflectiveQosAttribute;	/* OPTIONAL */
	long	*pDUSessionId;	/* OPTIONAL */
	long	*uLPduSessionAggregateMaximumBitRate;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBQoS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reflectiveQosAttribute_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DRBQoS;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBQoS_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBQoS_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBQoS_H_ */
#include "asn_internal.h"
