/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_DRXConfiguration_H_
#define	_DRXConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRXConfiguration__longDrxCycleLength {
	DRXConfiguration__longDrxCycleLength_ms10	= 0,
	DRXConfiguration__longDrxCycleLength_ms20	= 1,
	DRXConfiguration__longDrxCycleLength_ms32	= 2,
	DRXConfiguration__longDrxCycleLength_ms40	= 3,
	DRXConfiguration__longDrxCycleLength_ms60	= 4,
	DRXConfiguration__longDrxCycleLength_ms64	= 5,
	DRXConfiguration__longDrxCycleLength_ms70	= 6,
	DRXConfiguration__longDrxCycleLength_ms80	= 7,
	DRXConfiguration__longDrxCycleLength_ms128	= 8,
	DRXConfiguration__longDrxCycleLength_ms160	= 9,
	DRXConfiguration__longDrxCycleLength_ms256	= 10,
	DRXConfiguration__longDrxCycleLength_ms320	= 11,
	DRXConfiguration__longDrxCycleLength_ms512	= 12,
	DRXConfiguration__longDrxCycleLength_ms640	= 13,
	DRXConfiguration__longDrxCycleLength_ms1024	= 14,
	DRXConfiguration__longDrxCycleLength_ms1280	= 15,
	DRXConfiguration__longDrxCycleLength_ms2048	= 16,
	DRXConfiguration__longDrxCycleLength_ms2560	= 17,
	DRXConfiguration__longDrxCycleLength_ms5120	= 18,
	DRXConfiguration__longDrxCycleLength_ms1024odot	= 19
} e_DRXConfiguration__longDrxCycleLength;
typedef enum DRXConfiguration__shortDrxCycleLength {
	DRXConfiguration__shortDrxCycleLength_ms2	= 0,
	DRXConfiguration__shortDrxCycleLength_ms3	= 1,
	DRXConfiguration__shortDrxCycleLength_ms4	= 2,
	DRXConfiguration__shortDrxCycleLength_ms5	= 3,
	DRXConfiguration__shortDrxCycleLength_ms6	= 4,
	DRXConfiguration__shortDrxCycleLength_ms7	= 5,
	DRXConfiguration__shortDrxCycleLength_ms8	= 6,
	DRXConfiguration__shortDrxCycleLength_ms10	= 7,
	DRXConfiguration__shortDrxCycleLength_ms14	= 8,
	DRXConfiguration__shortDrxCycleLength_ms16	= 9,
	DRXConfiguration__shortDrxCycleLength_ms20	= 10,
	DRXConfiguration__shortDrxCycleLength_ms30	= 11,
	DRXConfiguration__shortDrxCycleLength_ms32	= 12,
	DRXConfiguration__shortDrxCycleLength_ms35	= 13,
	DRXConfiguration__shortDrxCycleLength_ms40	= 14,
	DRXConfiguration__shortDrxCycleLength_ms64	= 15,
	DRXConfiguration__shortDrxCycleLength_ms80	= 16,
	DRXConfiguration__shortDrxCycleLength_ms128	= 17,
	DRXConfiguration__shortDrxCycleLength_ms160	= 18,
	DRXConfiguration__shortDrxCycleLength_ms256	= 19,
	DRXConfiguration__shortDrxCycleLength_ms320	= 20,
	DRXConfiguration__shortDrxCycleLength_ms512	= 21,
	DRXConfiguration__shortDrxCycleLength_ms640	= 22
} e_DRXConfiguration__shortDrxCycleLength;

/* DRXConfiguration */
typedef struct DRXConfiguration {
	long	 longDrxCycleLength;
	long	 shortDrxCycleLength;
	long	 shortDrxCycleTimer;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRXConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_longDrxCycleLength_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_shortDrxCycleLength_23;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DRXConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_DRXConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_DRXConfiguration_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DRXConfiguration_H_ */
#include "asn_internal.h"
