/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_E_UTRACGI_H_
#define	_E_UTRACGI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PLMNIdentity.h"
#include "BIT_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-UTRACGI */
typedef struct E_UTRACGI {
	PLMNIdentity_t	 pLMNIdentity;
	BIT_STRING_t	 e_UTRACellIdentity;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_UTRACGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_UTRACGI;
extern asn_SEQUENCE_specifics_t asn_SPC_E_UTRACGI_specs_1;
extern asn_TYPE_member_t asn_MBR_E_UTRACGI_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E_UTRACGI_H_ */
#include "asn_internal.h"
