/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_E2SM_TS_RANFunctionDefinition_H_
#define	_E2SM_TS_RANFunctionDefinition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANFunctionName.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventTriggerStyles;
struct ReportStyles;
struct ControlStyles;

/* E2SM-TS-RANFunctionDefinition */
typedef struct E2SM_TS_RANFunctionDefinition {
	RANFunctionName_t	 rANFunctionName;
	struct E2SM_TS_RANFunctionDefinition__eventTriggerStyles_List {
		A_SEQUENCE_OF(struct EventTriggerStyles) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eventTriggerStyles_List;
	struct E2SM_TS_RANFunctionDefinition__reportStyles_List {
		A_SEQUENCE_OF(struct ReportStyles) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reportStyles_List;
	struct E2SM_TS_RANFunctionDefinition__controlStyles_List {
		A_SEQUENCE_OF(struct ControlStyles) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} controlStyles_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_TS_RANFunctionDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_TS_RANFunctionDefinition;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_TS_RANFunctionDefinition_H_ */
#include "asn_internal.h"
