/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_Inter_frequencyCellReselectionConfiguration_H_
#define	_Inter_frequencyCellReselectionConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ThresholdNR.h"
#include "NativeEnumerated.h"
#include "BOOLEAN.h"
#include "T-ReselectionNr-Sf.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing {
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_kHz15	= 0,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_kHz30	= 1,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_kHz60	= 2,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_kHz120	= 3,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_kHz240	= 4,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_spare3	= 5,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_spare2	= 6,
	Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing_spare1	= 7
} e_Inter_frequencyCellReselectionConfiguration__ssbSubcarrierSpacing;
typedef enum Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority {
	Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority_odot2	= 0,
	Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority_odot4	= 1,
	Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority_odot6	= 2,
	Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority_odot8	= 3
} e_Inter_frequencyCellReselectionConfiguration__cellReselectionSubpriority;
typedef enum Inter_frequencyCellReselectionConfiguration__q_OffsetFreq {
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_24	= 0,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_22	= 1,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_20	= 2,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_18	= 3,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_16	= 4,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_14	= 5,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_12	= 6,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_10	= 7,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_8	= 8,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_6	= 9,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_5	= 10,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_4	= 11,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_3	= 12,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_2	= 13,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB_1	= 14,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB0	= 15,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB1	= 16,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB2	= 17,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB3	= 18,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB4	= 19,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB5	= 20,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB6	= 21,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB8	= 22,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB10	= 23,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB12	= 24,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB14	= 25,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB16	= 26,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB18	= 27,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB20	= 28,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB22	= 29,
	Inter_frequencyCellReselectionConfiguration__q_OffsetFreq_dB24	= 30
} e_Inter_frequencyCellReselectionConfiguration__q_OffsetFreq;

/* Forward declarations */
struct Nr_MultiBandInfo;

/* Inter-frequencyCellReselectionConfiguration */
typedef struct Inter_frequencyCellReselectionConfiguration {
	long	 dlCarrierFrequency;
	struct Inter_frequencyCellReselectionConfiguration__nR_MultiBandInfo_List {
		A_SEQUENCE_OF(struct Nr_MultiBandInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nR_MultiBandInfo_List;
	long	*nrofSs_BlocksToAverage;	/* OPTIONAL */
	ThresholdNR_t	 absThreshSs_BlocksConsolidation;
	long	 ssbSubcarrierSpacing;
	BOOLEAN_t	*deriveSsb_IndexFromCell;	/* OPTIONAL */
	long	 qRxLevMin;
	long	*qQualMin;	/* OPTIONAL */
	long	*p_Max;	/* OPTIONAL */
	long	 t_ReselectionNr;
	T_ReselectionNr_Sf_t	 t_ReselectionNr_Sf;
	long	 threshX_HighP;
	long	 threshX_LowP;
	long	*threshX_HighQ;	/* OPTIONAL */
	long	*threshX_LowQ;	/* OPTIONAL */
	long	 cellReselectionPriority;
	long	*cellReselectionSubpriority;	/* OPTIONAL */
	long	 q_OffsetFreq;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Inter_frequencyCellReselectionConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ssbSubcarrierSpacing_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReselectionSubpriority_27;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_q_OffsetFreq_32;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Inter_frequencyCellReselectionConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_Inter_frequencyCellReselectionConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_Inter_frequencyCellReselectionConfiguration_1[18];

#ifdef __cplusplus
}
#endif

#endif	/* _Inter_frequencyCellReselectionConfiguration_H_ */
#include "asn_internal.h"
