/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_MeasurementResultNeighCells_Choice_H_
#define	_MeasurementResultNeighCells_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementResultNeighCells_Choice_PR {
	MeasurementResultNeighCells_Choice_PR_NOTHING,	/* No components present */
	MeasurementResultNeighCells_Choice_PR_measurementResultNr_List,
	MeasurementResultNeighCells_Choice_PR_measurementResultEutra_List
	/* Extensions may appear below */
	
} MeasurementResultNeighCells_Choice_PR;

/* Forward declarations */
struct MeasurementResultNr;
struct MeasurementResultEutra;

/* MeasurementResultNeighCells-Choice */
typedef struct MeasurementResultNeighCells_Choice {
	MeasurementResultNeighCells_Choice_PR present;
	union MeasurementResultNeighCells_Choice_u {
		struct MeasurementResultNeighCells_Choice__measurementResultNr_List {
			A_SEQUENCE_OF(struct MeasurementResultNr) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *measurementResultNr_List;
		struct MeasurementResultNeighCells_Choice__measurementResultEutra_List {
			A_SEQUENCE_OF(struct MeasurementResultEutra) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *measurementResultEutra_List;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementResultNeighCells_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementResultNeighCells_Choice;
extern asn_CHOICE_specifics_t asn_SPC_MeasurementResultNeighCells_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementResultNeighCells_Choice_1[2];
extern asn_per_constraints_t asn_PER_type_MeasurementResultNeighCells_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementResultNeighCells_Choice_H_ */
#include "asn_internal.h"
