/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_NeighborCellInformation_H_
#define	_NeighborCellInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NrCellContainers;
struct EutraCellContainers;

/* NeighborCellInformation */
typedef struct NeighborCellInformation {
	struct NeighborCellInformation__nRCellContainers_List {
		A_SEQUENCE_OF(struct NrCellContainers) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nRCellContainers_List;
	struct NeighborCellInformation__eUTRACellContainers_List {
		A_SEQUENCE_OF(struct EutraCellContainers) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eUTRACellContainers_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighborCellInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighborCellInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_NeighborCellInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighborCellInformation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NeighborCellInformation_H_ */
#include "asn_internal.h"
