/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_Non_dynamicSchedulingConfiguration_H_
#define	_Non_dynamicSchedulingConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Sps-Config.h"
#include "ConfiguredGrantConfig.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Non-dynamicSchedulingConfiguration */
typedef struct Non_dynamicSchedulingConfiguration {
	Sps_Config_t	 sPS_Config;
	ConfiguredGrantConfig_t	 configuredGrantConfig;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Non_dynamicSchedulingConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Non_dynamicSchedulingConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_Non_dynamicSchedulingConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_Non_dynamicSchedulingConfiguration_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Non_dynamicSchedulingConfiguration_H_ */
#include "asn_internal.h"
