/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_NrCellContainers_H_
#define	_NrCellContainers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRCGI.h"
#include "NativeInteger.h"
#include "OCTET_STRING.h"
#include "NativeEnumerated.h"
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NrCellContainers__sSBSubcarrierSpacing {
	NrCellContainers__sSBSubcarrierSpacing_kHz15	= 0,
	NrCellContainers__sSBSubcarrierSpacing_kHz30	= 1,
	NrCellContainers__sSBSubcarrierSpacing_kHz60	= 2,
	NrCellContainers__sSBSubcarrierSpacing_kHz120	= 3,
	NrCellContainers__sSBSubcarrierSpacing_kHz240	= 4,
	NrCellContainers__sSBSubcarrierSpacing_spare3	= 5,
	NrCellContainers__sSBSubcarrierSpacing_spare2	= 6,
	NrCellContainers__sSBSubcarrierSpacing_spare1	= 7
} e_NrCellContainers__sSBSubcarrierSpacing;
typedef enum NrCellContainers__qOffset {
	NrCellContainers__qOffset_dB_24	= 0,
	NrCellContainers__qOffset_dB_22	= 1,
	NrCellContainers__qOffset_dB_20	= 2,
	NrCellContainers__qOffset_dB_18	= 3,
	NrCellContainers__qOffset_dB_16	= 4,
	NrCellContainers__qOffset_dB_14	= 5,
	NrCellContainers__qOffset_dB_12	= 6,
	NrCellContainers__qOffset_dB_10	= 7,
	NrCellContainers__qOffset_dB_8	= 8,
	NrCellContainers__qOffset_dB_6	= 9,
	NrCellContainers__qOffset_dB_5	= 10,
	NrCellContainers__qOffset_dB_4	= 11,
	NrCellContainers__qOffset_dB_3	= 12,
	NrCellContainers__qOffset_dB_2	= 13,
	NrCellContainers__qOffset_dB_1	= 14,
	NrCellContainers__qOffset_dB0	= 15,
	NrCellContainers__qOffset_dB1	= 16,
	NrCellContainers__qOffset_dB2	= 17,
	NrCellContainers__qOffset_dB3	= 18,
	NrCellContainers__qOffset_dB4	= 19,
	NrCellContainers__qOffset_dB5	= 20,
	NrCellContainers__qOffset_dB6	= 21,
	NrCellContainers__qOffset_dB8	= 22,
	NrCellContainers__qOffset_dB10	= 23,
	NrCellContainers__qOffset_dB12	= 24,
	NrCellContainers__qOffset_dB14	= 25,
	NrCellContainers__qOffset_dB16	= 26,
	NrCellContainers__qOffset_dB18	= 27,
	NrCellContainers__qOffset_dB20	= 28,
	NrCellContainers__qOffset_dB22	= 29,
	NrCellContainers__qOffset_dB24	= 30
} e_NrCellContainers__qOffset;

/* NrCellContainers */
typedef struct NrCellContainers {
	NRCGI_t	 nRCgi;
	long	 nRPci;
	OCTET_STRING_t	 tAC;
	long	 nRCarrierArfcn;
	long	 sSBFrequency;
	long	 sSBSubcarrierSpacing;
	long	 qOffset;
	long	 qRxLevMinOffsetCell;
	long	 qQualLevMinOffsetCell;
	BOOLEAN_t	*isBlackCell;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NrCellContainers_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sSBSubcarrierSpacing_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_qOffset_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NrCellContainers;
extern asn_SEQUENCE_specifics_t asn_SPC_NrCellContainers_specs_1;
extern asn_TYPE_member_t asn_MBR_NrCellContainers_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _NrCellContainers_H_ */
#include "asn_internal.h"
