/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_O_Cu_CpCellMeasurement_H_
#define	_O_Cu_CpCellMeasurement_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRCGI.h"
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum O_Cu_CpCellMeasurement__cellStatus {
	O_Cu_CpCellMeasurement__cellStatus_outOfService	= 0,
	O_Cu_CpCellMeasurement__cellStatus_inService	= 1
} e_O_Cu_CpCellMeasurement__cellStatus;

/* O-Cu-CpCellMeasurement */
typedef struct O_Cu_CpCellMeasurement {
	NRCGI_t	 nRCgi;
	long	 cellStatus;
	long	 numberOfSupportedRrcConnections;
	long	*meanNumberOfRrcConnections;	/* OPTIONAL */
	long	 maxNumberOfRrcConnections;
	long	 numberOfRrcConnections;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} O_Cu_CpCellMeasurement_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellStatus_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_O_Cu_CpCellMeasurement;
extern asn_SEQUENCE_specifics_t asn_SPC_O_Cu_CpCellMeasurement_specs_1;
extern asn_TYPE_member_t asn_MBR_O_Cu_CpCellMeasurement_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _O_Cu_CpCellMeasurement_H_ */
#include "asn_internal.h"
