/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_O_Cu_CpCellConfiguration_H_
#define	_O_Cu_CpCellConfiguration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRCGI.h"
#include "NativeInteger.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasurementReportEventTriggerConfiguration;
struct NeighborCellInformation;
struct CommonCellReselectionConfiguration;
struct Intra_frequencyCellReselectionConfiguration;
struct Inter_frequencyCellReselectionConfiguration;
struct Inter_RATCellReselectionConfiguration;
struct LogicalChannelConfiguration;
struct DRXConfiguration;
struct SchedulingRequestConfiguration;
struct Non_dynamicSchedulingConfiguration;

/* O-Cu-CpCellConfiguration */
typedef struct O_Cu_CpCellConfiguration {
	NRCGI_t	 nRCgi;
	long	 nRPci;
	OCTET_STRING_t	 tAC;
	struct MeasurementReportEventTriggerConfiguration	*measurementReportEventTriggerConfiguration;	/* OPTIONAL */
	struct NeighborCellInformation	*neighborCellInformation;	/* OPTIONAL */
	struct CommonCellReselectionConfiguration	*commonCellReselectionConfiguration;	/* OPTIONAL */
	struct Intra_frequencyCellReselectionConfiguration	*intra_frequencyCellReselectionConfiguration;	/* OPTIONAL */
	struct Inter_frequencyCellReselectionConfiguration	*inter_frequencyCellReselectionConfiguration;	/* OPTIONAL */
	struct Inter_RATCellReselectionConfiguration	*inter_RATCellReselectionConfiguration;	/* OPTIONAL */
	struct LogicalChannelConfiguration	*logicalChannelConfiguration;	/* OPTIONAL */
	struct DRXConfiguration	*dRXConfiguration;	/* OPTIONAL */
	struct SchedulingRequestConfiguration	*schedulingRequestConfiguration;	/* OPTIONAL */
	struct Non_dynamicSchedulingConfiguration	*non_dynamicSchedulingConfiguration;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} O_Cu_CpCellConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_O_Cu_CpCellConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_O_Cu_CpCellConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_O_Cu_CpCellConfiguration_1[13];

#ifdef __cplusplus
}
#endif

#endif	/* _O_Cu_CpCellConfiguration_H_ */
#include "asn_internal.h"
