/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_O_DuCellMeasurement_H_
#define	_O_DuCellMeasurement_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRCGI.h"
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum O_DuCellMeasurement__cellStatus {
	O_DuCellMeasurement__cellStatus_outOfService	= 0,
	O_DuCellMeasurement__cellStatus_inService	= 1
} e_O_DuCellMeasurement__cellStatus;

/* O-DuCellMeasurement */
typedef struct O_DuCellMeasurement {
	NRCGI_t	 nRCgi;
	long	 cellStatus;
	long	*dLPrbUsageRatio;	/* OPTIONAL */
	long	*uLPrbUsageRatio;	/* OPTIONAL */
	long	*dLTotalAvailablePrbs;	/* OPTIONAL */
	long	*uLTotalAvailablePrbs;	/* OPTIONAL */
	long	*dLTotalPrbUsage;	/* OPTIONAL */
	long	*uLTotalPrbUsage;	/* OPTIONAL */
	long	*dLPrbUsedForDataTraffic;	/* OPTIONAL */
	long	*uLPrbUsedForDataTraffic;	/* OPTIONAL */
	long	*dLTotalPrbUsagePerMapped5QiPerCell;	/* OPTIONAL */
	long	*uLTotalPrbUsagePerMapped5QiPerCell;	/* OPTIONAL */
	long	*dLGbrPrb;	/* OPTIONAL */
	long	*dLNon_GbrPrb;	/* OPTIONAL */
	long	*totalNumberOfDlTbs;	/* OPTIONAL */
	long	*cellMacRate;	/* OPTIONAL */
	long	*distributionOfDlTotalPrbUsage;	/* OPTIONAL */
	long	*totalErrorNumberOfDlTbs;	/* OPTIONAL */
	long	*mCSDistributionInPdsch;	/* OPTIONAL */
	long	*meanNumberOfActiveUesInTheDlPerMapped5QiPerCell;	/* OPTIONAL */
	long	*maxNumberOfActiveUesInTheDlPerMapped5QiPerCell;	/* OPTIONAL */
	long	*dLPacketDropRateInGnb_Du;	/* OPTIONAL */
	long	*averageDelayDlInGnb_Du;	/* OPTIONAL */
	long	*dLF1_UPacketLossRate;	/* OPTIONAL */
	long	*dLThroughputPerMapped5QiPerCell;	/* OPTIONAL */
	long	*uLThroughputPerMapped5QiPerCell;	/* OPTIONAL */
	long	*dLNon_GbrThroughput;	/* OPTIONAL */
	long	*uLNon_GbrThroughput;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} O_DuCellMeasurement_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellStatus_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_O_DuCellMeasurement;
extern asn_SEQUENCE_specifics_t asn_SPC_O_DuCellMeasurement_specs_1;
extern asn_TYPE_member_t asn_MBR_O_DuCellMeasurement_1[28];

#ifdef __cplusplus
}
#endif

#endif	/* _O_DuCellMeasurement_H_ */
#include "asn_internal.h"
