/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "../nric_e2ap_v01.01.asn1"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ProtocolIE_ContainerPair_H_
#define	_ProtocolIE_ContainerPair_H_


#include "asn_application.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ContainerPair_H_ */
#include "asn_internal.h"
