/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_QosCharacteristics_Choice_H_
#define	_QosCharacteristics_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QosCharacteristics_Choice_PR {
	QosCharacteristics_Choice_PR_NOTHING,	/* No components present */
	QosCharacteristics_Choice_PR_non_dynamic5Qi,
	QosCharacteristics_Choice_PR_dynamic5Qi
	/* Extensions may appear below */
	
} QosCharacteristics_Choice_PR;

/* Forward declarations */
struct NonDynamic5QIDescriptor;
struct Dynamic5QIDescriptor;

/* QosCharacteristics-Choice */
typedef struct QosCharacteristics_Choice {
	QosCharacteristics_Choice_PR present;
	union QosCharacteristics_Choice_u {
		struct NonDynamic5QIDescriptor	*non_dynamic5Qi;
		struct Dynamic5QIDescriptor	*dynamic5Qi;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QosCharacteristics_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QosCharacteristics_Choice;
extern asn_CHOICE_specifics_t asn_SPC_QosCharacteristics_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_QosCharacteristics_Choice_1[2];
extern asn_per_constraints_t asn_PER_type_QosCharacteristics_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _QosCharacteristics_Choice_H_ */
#include "asn_internal.h"
