/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RANParameterType_H_
#define	_RANParameterType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANParameterType {
	RANParameterType_integer	= 0,
	RANParameterType_enumerated	= 1,
	RANParameterType_boolean	= 2,
	RANParameterType_bitstring	= 3,
	RANParameterType_octetstring	= 4,
	RANParameterType_printablestring	= 5
} e_RANParameterType;

/* RANParameterType */
typedef long	 RANParameterType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANParameterType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANParameterType;
extern const asn_INTEGER_specifics_t asn_SPC_RANParameterType_specs_1;
asn_struct_free_f RANParameterType_free;
asn_struct_print_f RANParameterType_print;
asn_constr_check_f RANParameterType_constraint;
ber_type_decoder_f RANParameterType_decode_ber;
der_type_encoder_f RANParameterType_encode_der;
xer_type_decoder_f RANParameterType_decode_xer;
xer_type_encoder_f RANParameterType_encode_xer;
oer_type_decoder_f RANParameterType_decode_oer;
oer_type_encoder_f RANParameterType_encode_oer;
per_type_decoder_f RANParameterType_decode_uper;
per_type_encoder_f RANParameterType_encode_uper;
per_type_decoder_f RANParameterType_decode_aper;
per_type_encoder_f RANParameterType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameterType_H_ */
#include "asn_internal.h"
