/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RANParameterName_H_
#define	_RANParameterName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PrintableString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RANParameterName */
typedef PrintableString_t	 RANParameterName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANParameterName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANParameterName;
asn_struct_free_f RANParameterName_free;
asn_struct_print_f RANParameterName_print;
asn_constr_check_f RANParameterName_constraint;
ber_type_decoder_f RANParameterName_decode_ber;
der_type_encoder_f RANParameterName_encode_der;
xer_type_decoder_f RANParameterName_decode_xer;
xer_type_encoder_f RANParameterName_encode_xer;
oer_type_decoder_f RANParameterName_decode_oer;
oer_type_encoder_f RANParameterName_encode_oer;
per_type_decoder_f RANParameterName_decode_uper;
per_type_encoder_f RANParameterName_encode_uper;
per_type_decoder_f RANParameterName_decode_aper;
per_type_encoder_f RANParameterName_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameterName_H_ */
#include "asn_internal.h"
