/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RANParameterID_H_
#define	_RANParameterID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RANParameterID */
typedef long	 RANParameterID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANParameterID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANParameterID;
asn_struct_free_f RANParameterID_free;
asn_struct_print_f RANParameterID_print;
asn_constr_check_f RANParameterID_constraint;
ber_type_decoder_f RANParameterID_decode_ber;
der_type_encoder_f RANParameterID_encode_der;
xer_type_decoder_f RANParameterID_decode_xer;
xer_type_encoder_f RANParameterID_encode_xer;
oer_type_decoder_f RANParameterID_decode_oer;
oer_type_encoder_f RANParameterID_encode_oer;
per_type_decoder_f RANParameterID_decode_uper;
per_type_encoder_f RANParameterID_encode_uper;
per_type_decoder_f RANParameterID_decode_aper;
per_type_encoder_f RANParameterID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameterID_H_ */
#include "asn_internal.h"
