/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ReportCellContainersByControl_H_
#define	_ReportCellContainersByControl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NRCGI.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReportUesByControl;

/* ReportCellContainersByControl */
typedef struct ReportCellContainersByControl {
	NRCGI_t	 nRCgi;
	struct ReportCellContainersByControl__reportUesByControl_List {
		A_SEQUENCE_OF(struct ReportUesByControl) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reportUesByControl_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportCellContainersByControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportCellContainersByControl;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportCellContainersByControl_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportCellContainersByControl_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ReportCellContainersByControl_H_ */
#include "asn_internal.h"
