/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RicControlOutcomeFormat_Choice_H_
#define	_RicControlOutcomeFormat_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RicControlOutcomeFormat_Choice_PR {
	RicControlOutcomeFormat_Choice_PR_NOTHING,	/* No components present */
	RicControlOutcomeFormat_Choice_PR_format1,
	RicControlOutcomeFormat_Choice_PR_format2,
	RicControlOutcomeFormat_Choice_PR_format3,
	RicControlOutcomeFormat_Choice_PR_format4,
	RicControlOutcomeFormat_Choice_PR_format5,
	RicControlOutcomeFormat_Choice_PR_format6,
	RicControlOutcomeFormat_Choice_PR_format7,
	RicControlOutcomeFormat_Choice_PR_format8,
	RicControlOutcomeFormat_Choice_PR_format9,
	RicControlOutcomeFormat_Choice_PR_format10
	/* Extensions may appear below */
	
} RicControlOutcomeFormat_Choice_PR;

/* Forward declarations */
struct E2SM_TS_ControlOutcomeFormat1;
struct E2SM_TS_ControlOutcomeFormat2;
struct E2SM_TS_ControlOutcomeFormat3;
struct E2SM_TS_ControlOutcomeFormat4;
struct E2SM_TS_ControlOutcomeFormat5;
struct E2SM_TS_ControlOutcomeFormat6;
struct E2SM_TS_ControlOutcomeFormat7;
struct E2SM_TS_ControlOutcomeFormat8;
struct E2SM_TS_ControlOutcomeFormat9;
struct E2SM_TS_ControlOutcomeFormat10;

/* RicControlOutcomeFormat-Choice */
typedef struct RicControlOutcomeFormat_Choice {
	RicControlOutcomeFormat_Choice_PR present;
	union RicControlOutcomeFormat_Choice_u {
		struct E2SM_TS_ControlOutcomeFormat1	*format1;
		struct E2SM_TS_ControlOutcomeFormat2	*format2;
		struct E2SM_TS_ControlOutcomeFormat3	*format3;
		struct E2SM_TS_ControlOutcomeFormat4	*format4;
		struct E2SM_TS_ControlOutcomeFormat5	*format5;
		struct E2SM_TS_ControlOutcomeFormat6	*format6;
		struct E2SM_TS_ControlOutcomeFormat7	*format7;
		struct E2SM_TS_ControlOutcomeFormat8	*format8;
		struct E2SM_TS_ControlOutcomeFormat9	*format9;
		struct E2SM_TS_ControlOutcomeFormat10	*format10;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RicControlOutcomeFormat_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RicControlOutcomeFormat_Choice;
extern asn_CHOICE_specifics_t asn_SPC_RicControlOutcomeFormat_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_RicControlOutcomeFormat_Choice_1[10];
extern asn_per_constraints_t asn_PER_type_RicControlOutcomeFormat_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RicControlOutcomeFormat_Choice_H_ */
#include "asn_internal.h"
