/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RicControlMessageFormat_Choice_H_
#define	_RicControlMessageFormat_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RicControlMessageFormat_Choice_PR {
	RicControlMessageFormat_Choice_PR_NOTHING,	/* No components present */
	RicControlMessageFormat_Choice_PR_format1,
	RicControlMessageFormat_Choice_PR_format2,
	RicControlMessageFormat_Choice_PR_format3,
	RicControlMessageFormat_Choice_PR_format4,
	RicControlMessageFormat_Choice_PR_format5,
	RicControlMessageFormat_Choice_PR_format6
	/* Extensions may appear below */
	
} RicControlMessageFormat_Choice_PR;

/* Forward declarations */
struct E2SM_TS_ControlMessageFormat1;
struct E2SM_TS_ControlMessageFormat2;
struct E2SM_TS_ControlMessageFormat3;
struct E2SM_TS_ControlMessageFormat4;
struct E2SM_TS_ControlMessageFormat5;
struct E2SM_TS_ControlMessageFormat6;

/* RicControlMessageFormat-Choice */
typedef struct RicControlMessageFormat_Choice {
	RicControlMessageFormat_Choice_PR present;
	union RicControlMessageFormat_Choice_u {
		struct E2SM_TS_ControlMessageFormat1	*format1;
		struct E2SM_TS_ControlMessageFormat2	*format2;
		struct E2SM_TS_ControlMessageFormat3	*format3;
		struct E2SM_TS_ControlMessageFormat4	*format4;
		struct E2SM_TS_ControlMessageFormat5	*format5;
		struct E2SM_TS_ControlMessageFormat6	*format6;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RicControlMessageFormat_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RicControlMessageFormat_Choice;
extern asn_CHOICE_specifics_t asn_SPC_RicControlMessageFormat_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_RicControlMessageFormat_Choice_1[6];
extern asn_per_constraints_t asn_PER_type_RicControlMessageFormat_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RicControlMessageFormat_Choice_H_ */
#include "asn_internal.h"
