/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RICFormatType_H_
#define	_RICFormatType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICFormatType */
typedef long	 RICFormatType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICFormatType;
asn_struct_free_f RICFormatType_free;
asn_struct_print_f RICFormatType_print;
asn_constr_check_f RICFormatType_constraint;
ber_type_decoder_f RICFormatType_decode_ber;
der_type_encoder_f RICFormatType_encode_der;
xer_type_decoder_f RICFormatType_decode_xer;
xer_type_encoder_f RICFormatType_encode_xer;
oer_type_decoder_f RICFormatType_decode_oer;
oer_type_encoder_f RICFormatType_encode_oer;
per_type_decoder_f RICFormatType_decode_uper;
per_type_encoder_f RICFormatType_encode_uper;
per_type_decoder_f RICFormatType_decode_aper;
per_type_encoder_f RICFormatType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICFormatType_H_ */
#include "asn_internal.h"
