/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RicIndicationMessageFormat_Choice_H_
#define	_RicIndicationMessageFormat_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RicIndicationMessageFormat_Choice_PR {
	RicIndicationMessageFormat_Choice_PR_NOTHING,	/* No components present */
	RicIndicationMessageFormat_Choice_PR_format1,
	RicIndicationMessageFormat_Choice_PR_format2,
	RicIndicationMessageFormat_Choice_PR_format3,
	RicIndicationMessageFormat_Choice_PR_format4,
	RicIndicationMessageFormat_Choice_PR_format5,
	RicIndicationMessageFormat_Choice_PR_format6,
	RicIndicationMessageFormat_Choice_PR_format7,
	RicIndicationMessageFormat_Choice_PR_format8,
	RicIndicationMessageFormat_Choice_PR_format9
	/* Extensions may appear below */
	
} RicIndicationMessageFormat_Choice_PR;

/* Forward declarations */
struct E2SM_TS_IndicationMessageFormat1;
struct E2SM_TS_IndicationMessageFormat2;
struct E2SM_TS_IndicationMessageFormat3;
struct E2SM_TS_IndicationMessageFormat4;
struct E2SM_TS_IndicationMessageFormat5;
struct E2SM_TS_IndicationMessageFormat6;
struct E2SM_TS_IndicationMessageFormat7;
struct E2SM_TS_IndicationMessageFormat8;
struct E2SM_TS_IndicationMessageFormat9;

/* RicIndicationMessageFormat-Choice */
typedef struct RicIndicationMessageFormat_Choice {
	RicIndicationMessageFormat_Choice_PR present;
	union RicIndicationMessageFormat_Choice_u {
		struct E2SM_TS_IndicationMessageFormat1	*format1;
		struct E2SM_TS_IndicationMessageFormat2	*format2;
		struct E2SM_TS_IndicationMessageFormat3	*format3;
		struct E2SM_TS_IndicationMessageFormat4	*format4;
		struct E2SM_TS_IndicationMessageFormat5	*format5;
		struct E2SM_TS_IndicationMessageFormat6	*format6;
		struct E2SM_TS_IndicationMessageFormat7	*format7;
		struct E2SM_TS_IndicationMessageFormat8	*format8;
		struct E2SM_TS_IndicationMessageFormat9	*format9;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RicIndicationMessageFormat_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RicIndicationMessageFormat_Choice;
extern asn_CHOICE_specifics_t asn_SPC_RicIndicationMessageFormat_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_RicIndicationMessageFormat_Choice_1[9];
extern asn_per_constraints_t asn_PER_type_RicIndicationMessageFormat_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RicIndicationMessageFormat_Choice_H_ */
#include "asn_internal.h"
