/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RicReportActionDefinitionFormat_Choice_H_
#define	_RicReportActionDefinitionFormat_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RicReportActionDefinitionFormat_Choice_PR {
	RicReportActionDefinitionFormat_Choice_PR_NOTHING,	/* No components present */
	RicReportActionDefinitionFormat_Choice_PR_format1
	/* Extensions may appear below */
	
} RicReportActionDefinitionFormat_Choice_PR;

/* Forward declarations */
struct E2SM_TS_ReportActionDefinitionFormat1;

/* RicReportActionDefinitionFormat-Choice */
typedef struct RicReportActionDefinitionFormat_Choice {
	RicReportActionDefinitionFormat_Choice_PR present;
	union RicReportActionDefinitionFormat_Choice_u {
		struct E2SM_TS_ReportActionDefinitionFormat1	*format1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RicReportActionDefinitionFormat_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RicReportActionDefinitionFormat_Choice;
extern asn_CHOICE_specifics_t asn_SPC_RicReportActionDefinitionFormat_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_RicReportActionDefinitionFormat_Choice_1[1];
extern asn_per_constraints_t asn_PER_type_RicReportActionDefinitionFormat_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RicReportActionDefinitionFormat_Choice_H_ */
#include "asn_internal.h"
