/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RICStyleType_H_
#define	_RICStyleType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICStyleType */
typedef long	 RICStyleType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICStyleType;
asn_struct_free_f RICStyleType_free;
asn_struct_print_f RICStyleType_print;
asn_constr_check_f RICStyleType_constraint;
ber_type_decoder_f RICStyleType_decode_ber;
der_type_encoder_f RICStyleType_encode_der;
xer_type_decoder_f RICStyleType_decode_xer;
xer_type_encoder_f RICStyleType_encode_xer;
oer_type_decoder_f RICStyleType_decode_oer;
oer_type_encoder_f RICStyleType_encode_oer;
per_type_decoder_f RICStyleType_decode_uper;
per_type_encoder_f RICStyleType_encode_uper;
per_type_decoder_f RICStyleType_decode_aper;
per_type_encoder_f RICStyleType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICStyleType_H_ */
#include "asn_internal.h"
