/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ServingFrequencyInformation_H_
#define	_ServingFrequencyInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingFrequencyInformation__cellReselectionSubpriority {
	ServingFrequencyInformation__cellReselectionSubpriority_odot2	= 0,
	ServingFrequencyInformation__cellReselectionSubpriority_odot4	= 1,
	ServingFrequencyInformation__cellReselectionSubpriority_odot6	= 2,
	ServingFrequencyInformation__cellReselectionSubpriority_odot8	= 3
} e_ServingFrequencyInformation__cellReselectionSubpriority;

/* ServingFrequencyInformation */
typedef struct ServingFrequencyInformation {
	long	 s_NonIntraSearchP;
	long	 s_NonIntraSearchQ;
	long	 threshServingLowP;
	long	 threshServingLowQ;
	long	 cellReselectionPriority;
	long	 cellReselectionSubpriority;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServingFrequencyInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cellReselectionSubpriority_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ServingFrequencyInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_ServingFrequencyInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_ServingFrequencyInformation_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ServingFrequencyInformation_H_ */
#include "asn_internal.h"
