/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_Sps_Config_H_
#define	_Sps_Config_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Sps_Config__periodicity {
	Sps_Config__periodicity_ms10	= 0,
	Sps_Config__periodicity_ms20	= 1,
	Sps_Config__periodicity_ms32	= 2,
	Sps_Config__periodicity_ms40	= 3,
	Sps_Config__periodicity_ms64	= 4,
	Sps_Config__periodicity_ms80	= 5,
	Sps_Config__periodicity_ms128	= 6,
	Sps_Config__periodicity_ms160	= 7,
	Sps_Config__periodicity_ms320	= 8,
	Sps_Config__periodicity_ms640	= 9,
	Sps_Config__periodicity_spare6	= 10,
	Sps_Config__periodicity_spare5	= 11,
	Sps_Config__periodicity_spare4	= 12,
	Sps_Config__periodicity_spare3	= 13,
	Sps_Config__periodicity_spare2	= 14,
	Sps_Config__periodicity_spare1	= 15
} e_Sps_Config__periodicity;

/* Sps-Config */
typedef struct Sps_Config {
	long	 periodicity;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Sps_Config_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_periodicity_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Sps_Config;
extern asn_SEQUENCE_specifics_t asn_SPC_Sps_Config_specs_1;
extern asn_TYPE_member_t asn_MBR_Sps_Config_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Sps_Config_H_ */
#include "asn_internal.h"
