/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-TS-IEs"
 * 	found in "E2SM-TS_ASN1_freeze_ver_0222.asn"
 * 	`asn1c -S /root/nric/asn1c/skeletons/ -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_T_ReselectionNr_Sf_H_
#define	_T_ReselectionNr_Sf_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T_ReselectionNr_Sf__sf_Medium {
	T_ReselectionNr_Sf__sf_Medium_odot25	= 0,
	T_ReselectionNr_Sf__sf_Medium_odot5	= 1,
	T_ReselectionNr_Sf__sf_Medium_odot75	= 2,
	T_ReselectionNr_Sf__sf_Medium_n1dot0	= 3
} e_T_ReselectionNr_Sf__sf_Medium;
typedef enum T_ReselectionNr_Sf__sf_High {
	T_ReselectionNr_Sf__sf_High_odot25	= 0,
	T_ReselectionNr_Sf__sf_High_odot5	= 1,
	T_ReselectionNr_Sf__sf_High_odot75	= 2,
	T_ReselectionNr_Sf__sf_High_n1dot0	= 3
} e_T_ReselectionNr_Sf__sf_High;

/* T-ReselectionNr-Sf */
typedef struct T_ReselectionNr_Sf {
	long	*sf_Medium;	/* OPTIONAL */
	long	*sf_High;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T_ReselectionNr_Sf_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sf_Medium_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sf_High_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_T_ReselectionNr_Sf;
extern asn_SEQUENCE_specifics_t asn_SPC_T_ReselectionNr_Sf_specs_1;
extern asn_TYPE_member_t asn_MBR_T_ReselectionNr_Sf_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _T_ReselectionNr_Sf_H_ */
#include "asn_internal.h"
